fix animations breaking with dummies
o3de/o3de pull request #10039
Opened 2022-06-10 09:06 UTC by CyaNinix

2022-06-10 20:14 UTC, lmbr-pip commented
Please provide some information for this change. What is it changing and why? How did you test? etc

2022-06-10 21:17 UTC, CyaSid commented
Hello!

We have a couple old FBXs that contains "dummy nodes" (bones with no vertex associated), that are used as attachment points for equipments (swords, helmets, etc).
The for-loop inside the animation loader goes through all nodes to see if a "pivot" (dummy node) exists. Assimp stores dummy nodes as 3 separate nodes, one for each type of transformation (translation, rotation, scaling), and the loader creates a single node from these 3 separate nodes. These nodes are then stored in the combinedAnimation vector.

However, the following code:
````
if (!combinedAnimations.empty())
{
    boneAnimations.swap(combinedAnimations);
}
````
causes all animations that are not coming from dummy nodes to be discarded, if there is at least one dummy node in the skeleton.

The fix made in this pull request might not be the most elegant (we try keeping our engine fixes as small as possible), but with it our animations finally work.

I can't share the broken FBXs here for you to test, however we can probably open a ticket on the private repository @AMZN-alexpete opened for us not long ago, if you need it. Otherwise @AMZN-Gene definitely has that FBX somewhere, we have been fixing that bug again and again since Lumberyard 1.17 !

2022-06-13 11:11 UTC, hultonha commented
Thanks for all the additional info @CyaNinix! Really helpful, @amzn-rhhong has been hard at working fixing a number of other import issues so would be well placed to take a look at this PR. I'm afraid @AMZN-Gene is out for a little while so potentially if we could chat on Discord and you share the asset directly for us to test that would be super helpful. Thank you! (my Discord username is `tomhh (hultonha) [Amazon]`. Thanks!

2022-06-15 18:34 UTC, amzn-mike approved these changes

2022-06-17 02:42 UTC, amzn-rhhong requested changes
I think we need to be cautious on the impact of this change and would definitely needs some test asset and adding automation tests to verify it.

Can you elaborate on "(the original code) causes all animations that are not coming from dummy nodes to be discarded, if there is at least one dummy node in the skeleton"? Are you saying the dummy node (attachment node without skinned to any vert) animation will not exported? or having a dummy node will causes any non-dummy node animation to fail in export?

I'm sorry that it looks like this bug has an reoccurring pattern since LY1.17. The latest change move to AssImp might have caused it to re-surface. Would be great to have some test assets so we can get to the root cause and fix it once for all.

2022-09-08 11:51 UTC, hultonha commented
Any update on this issue @CyaNinix and @amzn-rhhong? I just want to understand what would be the best thing to do with this PR if there are further things we need to test to ensure there aren't any unintended consequences or regressions. Thanks!

2022-11-29 10:10 UTC, hultonha commented
@amzn-rhhong Would you be able to give an update on how you think we should move forward with this PR - are there some tests we can run to ensure this doesn't have any unintended consequences? It would be great to either get to the stage where we can merge this (or failing that close it or request changes)

2026-07-05 12:25 UTC, closed without merging