fix system dll dependencies loading
o3de/o3de pull request #10040
Opened 2022-06-10 09:07 UTC by CyaNinix

2022-06-10 16:04 UTC, lumberyard-employee-dm requested changes

2022-06-10 16:04 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
> +                    m_handle = LoadLibraryW(fileNameW);
Could you provide a more in depth description on why this change is needed?
The summary say that is to fix system dll dependency loading, but this change is actually trying to add the directory of the current dll/executable memory space [into the list of directories to load](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw#parameters).

2022-06-10 20:44 UTC, CyaSid commented on Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
> +                    m_handle = LoadLibraryW(fileNameW);
Hello @amzn-phist ,

We need to dynamically load a 3rd party DLL inside one of our gems, and we are using AZ::DynamicModuleHandle::Create to do the job. Our DLL requires some other DLLs to be present and calling LoadLibrary would try loading these as well. If all the DLLs are in the same folder as the executable, everything works as intended.
However, the AssetProcessor/Builder and the GameLauncher executables aren't located in the same folder (AssetProcessor/Builder are contained in the SDK binaries folder, GameLauncher in our project binaries folder). This causes the asset processor to fail loading the DLL, even if we call AZ::DynamicModuleHandle::Create with the full DLL path.
By calling first LoadLibraryExW with the LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR flag set, we ensure that the folder containing the DLL we are trying to load will be added to the search path, so that other required DLLs located in the same folder would be found as well.
We don't want to put the 3rd party in the Engine folder because it is game-dependent.

2022-06-10 23:14 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
> +                    m_handle = LoadLibraryW(fileNameW);
So is your gem module statically linking to the 3rdParty DLL?
So that when your gem module loads, the 3rdParty DLL loads?

Or is your gem module dynamically loading the 3rdParty DLL at runtime?
In the latter case, using an absolute path with [LoadLibraryW](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw#parameters) should work

> If the string specifies a full path, the function searches only that path for the module.

For your 3rdParty DLL case, are you sure the `fileNameW` value is set to the correct absolute path of that 3rdParty DLL?

Also could that 3rdParty DLL be failing to load because it can't load another dependent dll?

2022-06-13 15:02 UTC, lawsonamzn commented on Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
> +                    m_handle = LoadLibraryW(fileNameW);
Wouldn't another way that works be to add the specific paths you need to load DLLs from to the PATH (you can do this programatically to add it to the env of the current process)?   Going from absolute path to using these flags globally would potentially mean a larger surface area for DLL injection exploits.

2022-12-01 19:38 UTC, lumberyard-employee-dm commented
@CyaNinix We are closing this PR for now as we believe this change has a security concern with adding the DLL load path to the list of search paths for loading dependent dlls.
This can potentially allow a user to load a dll with the same name as a system dll that is next to loaded module dll from an untrusted directory.

A workaround is to have the user code add the module dll directory to the list of search directories before loading using [AddDllDirectory](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory).
With that the O3DE WinAPI module loading code isn't modified.

2022-12-01 19:38 UTC, closed without merging