Material: Fix Compile() when NeedsCompile() = false
o3de/o3de pull request #10052
Opened 2022-06-10 13:10 UTC by CyaNinix

When a material property is updated on a material that doesn't have this property (which of course is a mistake), the material becomes stuck and cannot compile. 

As `Material::CanCompile` will return false (because its srg will not be queued for compilation), the material will simply try to compile every tick forever.

A simple fix is to check if the material compilation is required.

2022-06-13 15:31 UTC, cgalvan requested changes

2022-06-13 15:38 UTC, cgalvan commented on Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
> +                return true;
Wow you are fast! Kicking off AR

2022-06-13 18:04 UTC, cgalvan commented
@CyaNinix This unit test failed with this change:
```
[2022-06-13T16:57:09.946Z] [ RUN      ] MaterialTests.TestSetPropertyValueWhenValueIsUnchanged
[2022-06-13T16:57:09.946Z] D:/workspace/o3de/Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp(357): error: Value of: material->Compile()
[2022-06-13T16:57:09.946Z]   Actual: true
[2022-06-13T16:57:09.946Z] Expected: false
[2022-06-13T16:57:09.946Z] [  FAILED  ] MaterialTests.TestSetPropertyValueWhenValueIsUnchanged (14 ms)
```

2022-06-14 07:10 UTC, CyaNinix commented
> This unit test failed with this change:

Indeed, but then with this change the behavior of Compile() changes when a property value is unchanged. Should I fix the test?

2022-06-14 16:55 UTC, cgalvan commented
> > This unit test failed with this change:
> 
> Indeed, but then with this change the behavior of Compile() changes when a property value is unchanged. Should I fix the test?

Yeah I think in this case since we changed the exact behavior the test was trying to validate it is valid to update the test.

2022-06-15 15:24 UTC, cgalvan approved these changes

2022-06-15 20:16 UTC, gadams3 approved these changes

2022-06-15 20:16 UTC, merged