Enhance the FrameCaptureSystemComponent to support multiple active captures at the same time
o3de/o3de pull request #10260
Opened 2022-06-21 23:57 UTC by rgba16f

FrameCaptureBus now returns a capture id with each request. 
Calling code uses the capture id to identify when it's capture is complete.
Update any code that uses the affected API.

2022-06-27 15:44 UTC, galibzon approved these changes

2022-06-27 16:37 UTC, gadams3 requested changes

2022-06-27 18:45 UTC, gadams3 commented on Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.cpp
> +            // if the start capture call fails the capture will be retried next tick.
Discussed offline. Changes for addressing the bus will be done in a follow-up PR

2022-06-27 22:49 UTC, rgba16f commented on Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
>          AZ::RPI::RPISystemInterface::Get()->RegisterScene(m_scene);
Removed that line.

2022-06-27 23:47 UTC, gadams3 approved these changes

2022-06-28 21:52 UTC, rgba16f commented on Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp
> +                    const bool frameCaptureScope = scopeName.starts_with("FrameCapture_");
I don't disagree that this approach is brittle. The scope solution would need implementations for every RHI though. Is there an existing way to add DX12 specific workarounds?

2022-06-28 23:38 UTC, rgba16f commented on Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
>              }
Added suggested comments

2022-06-28 23:38 UTC, rgba16f commented on Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.h
> +            struct CaptureState
Added a small class header comment

2022-06-28 23:38 UTC, rgba16f commented on Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.h
> +            class CaptureHandle
Added a small class header comment

2022-06-28 23:39 UTC, rgba16f commented on Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp
> +                    const bool frameCaptureScope = scopeName.starts_with("FrameCapture_");
Removed this hack, it wasn't fixing the original issue (1 camera on DX12 always returns black data).

2022-06-29 14:58 UTC, merged