bugfix: fix minimization/maximization button for the editor
o3de/o3de pull request #10359
Opened 2022-06-26 03:51 UTC by pollend

Signed-off-by: Michael Pollind <mpollind@gmail.com>

## What does this PR do?

use `WindowStateChange` event from the main window to determine the maximization state of the button. relying on just the user action of pressing the button does not cover all cases where the window is maximized/minimized.

## How was this PR tested?

test both clicking on the minimize/maximize button and also double clicking on the window.

ref: https://github.com/o3de/o3de/issues/10048

2022-06-26 08:11 UTC, gadams3 approved these changes

2022-06-27 15:38 UTC, pollend commented
I forget can you change the main parent that the widget was assigned to. would I need to catch the case where the window changes?

2022-06-27 15:50 UTC, cgalvan requested changes

2022-06-27 15:50 UTC, cgalvan commented on Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
>  #include <QTimer>
Nitpick: Since you're removing the `QTimer::singleShot` you can remove the `QTimer` include as well

2022-06-27 15:50 UTC, cgalvan commented on Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
> +#include <QEvent>
Uber nitpick: Could put `QEvent` just below `QApplication` for alphabetical ordering

2022-06-27 15:50 UTC, cgalvan commented on Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
> +        }
This logic should only run if `m_buttonType == DockBarButton::MaximizeButton`. So could either do that check here, or instead could only install the event filter for that case.

2022-06-28 15:14 UTC, cgalvan approved these changes

2022-06-28 15:15 UTC, cgalvan commented
Thanks for addressing the feedback @pollend ! I've kicked off an AR run now.

2022-06-28 17:01 UTC, merged