Small Operator Nodes
o3de/o3de pull request #10533
Opened 2022-07-05 23:32 UTC by mddvisu

Added "Small Operator" nodes to script canvas which are meant to perform small operations on data without taking up much space in the graph. As of now these nodes do not parse, so they are hidden by default. To show these nodes in the palette, flip the ed_showSmallOperatorNodes cvar to true, and they will appear in the node palette under Math/Small Operators.

These nodes are created in a more data-driven way, keeping the future direction of ScriptCanvas in mind. Instead of the information for these nodes being stored in an inherited class of Node, these nodes are created through user data, allowing for many different small operator nodes to be created in very little time.

<img width="799" alt="Small Operator Nodes" src="https://user-images.githubusercontent.com/105814224/177402509-0c0c0435-1f6d-4f45-8e20-444ef949fc9c.png">

2022-07-07 21:47 UTC, carlitosan requested changes

2022-07-07 21:47 UTC, carlitosan commented on Gems/GraphCanvas/Code/Source/Components/Nodes/General/GeneralNodeLayoutComponent.cpp
> +            Qt::Orientation layoutOrientation = style.GetAttribute(Styling::Attribute::LayoutOrientation, Qt::Vertical);
Is this new member bool necessary? Can you query the current LayoutOrientation on demand?

2022-07-07 21:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.h
> +        virtual ~SmallOperatorCreationData() = default;
You don't need this destructor definition, or for it to be virtual.

2022-07-07 21:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.h
> +        AZ_RTTI(SmallOperatorCreationData, "{A7DE9ECF-81F9-4A03-B3E4-3510591A50BB}");
Use AZ_TYPE_INFO

2022-07-07 21:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.cpp
> +        node->SetNodeStyle(GraphCanvas::Styling::Elements::Small);
Pipe this request through the DataDrivenNode pipeline, and then remove references to any SmallOperatorNode classes, names. Just use the data-driven pipeline that you have provided.

2022-07-07 21:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp
> +        if (m_name == "")
if (m_name.empty())

2022-07-07 21:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp
> +    void Node::SetNodenodeLexicalId(const AZ::Crc32& nodeLexicalId)
SetNodeLexicalId

2022-07-07 21:47 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.h
> +    struct RegisterSmallOperatorNodeInformation
This all can just be the DataDrivenTypeInfo, and doesn't need to refer to small operators

2022-07-07 21:56 UTC, lsemp3d approved these changes

2022-07-18 17:45 UTC, carlitosan approved these changes

2022-07-19 23:11 UTC, merged