Benblac/kitbash conversion tool
o3de/o3de pull request #10649
Opened 2022-07-13 16:40 UTC by benblack75

## What does this PR do?

This script assists the conversion of Kitbash3d FBX assets into O3DE formatted assets. It takes the entire kitbash set and separates into individual elements. This is an update to an older script- not all functionality is working yet, but for basic conversion it works as advertised.

## How was this PR tested?
I tested several runs locally with no issues. The script does need to run through the DCCsi currently in order to properly access environment and Python libraries

2022-07-13 18:43 UTC, HogJonny-AMZN requested changes
only request is a simple set of instructions in a read.me in this folder.

2022-08-15 15:10 UTC, shawstar reviewed
KitbashCoversionTool and other tools like this. Best to include a readme.md in tools like this, as it would be nice to see instructions and features of the till right in git. Maybe we can generate one from Docstrings?

2022-08-15 15:11 UTC, shawstar requested changes
Needs readme.md

2022-08-15 18:02 UTC, shawstar commented on Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Maya/Tools/KitbashConversion/process_fbx_file.py
> +ProcessFbxFile(sys.argv[1], sys.argv[2], sys.argv[3].replace('/', '\\'), sys.argv[4])
Looks pretty clean, there are more os methods that could be Pathlib.

2026-07-05 12:31 UTC, closed without merging