FileWatcher_linux: Don't give up on a directory if a sub-entry couldn't be watched
o3de/o3de pull request #11248
Opened 2022-08-12 07:34 UTC by RoaldFre

## What does this PR do?

The file watcher on Linux used to give up on an entire directory if one of its sub-entries couldn't be watched (e.g. due to a permission problem). This PR modifies the behaviour such that the file watcher continues to (try to) add the remaining sub-entries of that directory.

## How was this PR tested?

Tested manually by adding some files to a watched folder with non-read permission.

2022-08-12 15:17 UTC, lumberyard-employee-dm commented on Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
> +            continue;
Seems like we should continue only if errno matches [EACCES](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html) which indicates a permission problem

2022-08-16 10:35 UTC, RoaldFre commented
I have improved the error handling and reporting further as per feedback (including a hint to the user for the ENOSPC case), factored out repeated code and updated the formatting of the touched parts following the current style guidelines.

The previous CI failure happened in the Windows test suite (note that this PR should only affect the Linux side): the Gem::Atom_RPI.Tests.main failure seems related to https://github.com/o3de/o3de/pull/11269; the segfault in AZ::AzCore.Tests.main seems related to https://github.com/o3de/o3de/issues/11238 . I've merged the dev branch to get the fix for the first issue.

2022-08-16 13:29 UTC, spham-amzn approved these changes

2022-08-16 15:34 UTC, spham-amzn commented on Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
> +                    "Giving up on directory %s due to errors", cleanPath.toUtf8().constData());
maybe helpful to capture the errno value in the warning message

2022-08-18 22:28 UTC, AMZN-stankowi approved these changes
After addressing the other feedback, especially the improved error message, this looks good to go. It's lacking automated tests, I've cut a ticket to our backlog to add those later, unless you feel comfortable adding them yourself soon.

2022-08-19 01:33 UTC, byrcolin approved these changes

2022-08-22 17:52 UTC, lmbr-pip commented
Looked this failed its first AR run: https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-11248/1/ due to a SEGFault and an ATOM failure on windows

Am trying AR run again as these are just Linux changes but @RoaldFre we may need to merge in latest to get around these AR failures.

2022-08-23 10:16 UTC, RoaldFre commented on Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
> +    auto tryToWatch = [&](const QString& pathStr) -> bool {
No deep reason. I've now split it off to a method which makes the errno handling a bit more explicit.

2022-08-23 10:24 UTC, RoaldFre commented
I've upgraded the TryToWatch() function from a lambda to a proper method (with more explicit handling of the errno), and the errno is now directly reported in warnings as well as per feedback.

I'll leave the automated tests to someone more familiar with the testing framework if possible ;-).

The latest AR (before this last commit) seemed successful so I've left the branch there to avoid another (spammy?) dev branch merge commit for now.

2022-09-15 23:36 UTC, lmbr-pip commented
Interestingly this passed on AR: https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-11248/ but is not approved for build. Need to follow up with testing team

2022-09-15 23:49 UTC, amzn-changml commented
This is good to go, as it passed validation previously, but GitHub Actions is failing to fire. We can bypass this as soon as we get word that we're ready to merge

2022-09-16 00:09 UTC, lumberyard-employee-dm requested changes

2022-09-16 00:09 UTC, lumberyard-employee-dm commented on Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
> +    const char* path = pathStr.toUtf8().constData();
This is a dangling pointer here.

2022-09-16 00:13 UTC, lumberyard-employee-dm commented
> This is good to go, as it passed validation previously, but GitHub Actions is failing to fire. We can bypass this as soon as we get word that we're ready to merge

This isn't ready to merge yet.
There is major issue with referencing invalid memory.

2022-09-16 10:00 UTC, RoaldFre commented
Good catch! That dangling pointer has now been fixed as suggested.

2022-09-16 15:13 UTC, lumberyard-employee-dm approved these changes
Thanks for the address the dangling pointer issue

2022-09-19 15:17 UTC, merged