Use GraphCanvas node palette in EMFX context menu
o3de/o3de pull request #11595
Opened 2022-08-26 16:37 UTC by MiKom

- Original node palette dock window is still there but hidden by default
  in the layout
- Decision of what font color should be used for inactive nodes in the
  NodePaletteTreeWidget was moved from model to the delegate. The model
  doesn't have the information about the default text color so it
  wouldn't what color to make transparent. I investigated delegating
  the decision of the inactive color to Qt through passing the
  inactivity info from model's ::flags() method (Qt::ItemIsEnabled).
  However, this caused some ugly artifacts. Inactive tree items where
  highlighted partially (on the expand triangle)
- Nodes don't yet have the colored rectangle next to them. For this
  I'd like to use icon engine developed for #10961. Thus it will be done
  in a follow-up PR.

Fixes #10963

Signed-off-by: Miłosz Kosobucki <milosz@kosobucki.pl>

## What does this PR do?

Adds the node palette tree item to context menu in EMotionFX. Same type as in {Script,Landscape,Material}Canvas

## How was this PR tested?

Unit tests were updated to use the new API and I tested it manually.

2022-08-26 16:38 UTC, MiKom commented
Please let me know if you want me to add the icons in the tree in this PR or can we get this one through and add icons later.

2022-08-26 16:47 UTC, MiKom commented
That's how it looks:

https://user-images.githubusercontent.com/104767/186953495-41d966ed-22f0-4b72-9694-7a3d1d084227.mp4

2022-08-29 15:25 UTC, cgalvan commented on Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.h
> +    static constexpr GraphCanvas::EditorId AnimGraphEditorId = AZ_CRC("AnimGraphEditor",  0xf44fce98);
Nit: Let the compiler compute the hash for us

```suggestion
    static constexpr GraphCanvas::EditorId AnimGraphEditorId = AZ_CRC_CE("AnimGraphEditor");
```

2022-08-29 15:26 UTC, cgalvan commented on Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
> +#include <QDebug>
Nit: Can remove `QDebug`

2022-08-29 15:32 UTC, cgalvan commented on Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp
> +                               EMotionFX::AnimGraphObject* focusedGraphObject)
Nit: Looks like some extra whitespace here?

2022-08-29 20:03 UTC, cgalvan commented on Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.h
> +    static constexpr GraphCanvas::EditorId AnimGraphEditorId = AZ_CRC("AnimGraphEditor",  0xf44fce98);
Actually the hash was a mismatch which failed the validation on AR, so even more of a reason to use `AZ_CRC_CE` instead :)

```
VALIDATOR_FAILED: CrcValidator /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.h::CrcValidator FAILED - Source file contains a CRC mismatch!
[2022-08-29T18:10:46.857Z]          AZ_CRC("AnimGraphEditor", 0xf44fce98), expected value 0xfdba7ae7
```

2022-08-29 20:04 UTC, cgalvan requested changes
The above comments are mostly nits except the CRC one needs to be updated to pass validation

2022-08-30 14:53 UTC, cgalvan approved these changes

2022-08-30 14:54 UTC, cgalvan commented
> Hey @cgalvan Thanks for review and all the comments. I adressed them in the new commits.

Thanks @MiKom ! I've approved and kicked off a new AR.

2022-08-30 17:59 UTC, lsemp3d approved these changes

2022-08-30 17:59 UTC, alexmontAmazon approved these changes

2022-08-30 18:00 UTC, merged