Added typed exceptions to LyTT.
o3de/o3de pull request #11694
Opened 2022-08-31 22:51 UTC by AMZN-scspaldi

Signed-off-by: scspaldi <scspaldi@amazon.com>

## What does this PR do?

Adds typed exceptions to LyTT and EditorTest to clarify where exceptions are coming from.

## How was this PR tested?

Tested locally and on AR.

2022-08-31 23:05 UTC, evanchia-ly-sdets approved these changes

2022-09-01 18:28 UTC, Kadino requested changes
Looks pretty good! I like how simple most of this change landed, with some requests:

2022-09-01 20:42 UTC, AMZN-scspaldi commented on Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
> +            raise EditorToolsFrameworkException("Must have at least one executable")
What do you mean by "clamp it to one"?

2022-09-01 20:52 UTC, Kadino commented on Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
> +            raise EditorToolsFrameworkException("Must have at least one executable")
If less than one, set to one.

2022-09-02 17:13 UTC, Kadino approved these changes

2022-09-06 19:46 UTC, merged