Add world-space transform to RayTracingSceneSrg::MeshInfo
o3de/o3de pull request #12220
Opened 2022-09-27 12:11 UTC by mprettner-huawei

## What does this PR do?

This PR adds the world-space transformation of a mesh to the `MeshInfo` struct of the `RayTracingSceneSrg`. This struct already contains `m_worldInvTranspose`, which only consists of the transpose-inverse of the 3x3 rotation matrix of the mesh.
The new field `m_world` is useful if a transformation from the model-space from a given `MeshInfo`-struct instance to world-space is required.

## How was this PR tested?

Internal testing shows that this code works, but since the `MeshInfo` struct is not used in public code (in O3DE or AtomSampleViewer), there is no test coverage other than that.

2022-09-27 16:42 UTC, invertednormal commented
Isn't this the same thing that's stored in the transform service feature processor? If so it should already be possible to look up this matrix in the shader by object ID

2022-09-28 09:18 UTC, mprettner-huawei commented
Yes, you are right, the `TransformServiceFeatureProcessor` provides the object-to-world transformation to `SceneSrg`.
So what is the reason for the `m_worldInvTranspose` member in `MeshInfo`, since it is also in `SceneSrg`?

2022-09-28 17:57 UTC, invertednormal commented
> Yes, you are right, the `TransformServiceFeatureProcessor` provides the object-to-world transformation to `SceneSrg`. So what is the reason for the `m_worldInvTranspose` member in `MeshInfo`, since it is also in `SceneSrg`?

Not sure, possibly added by mistake?

2022-09-28 18:51 UTC, dmcdiarmid-ly commented
At the time the SceneSrg was not accessible from the hit shader, but that has been resolved.

2022-09-28 18:53 UTC, dmcdiarmid-ly requested changes
Why is this necessary when you can already get the transform by calling ObjectToWorld3x4() in the shader?

2022-09-29 06:47 UTC, mprettner-huawei commented
Ok, since this is clearly not necessary I will close this PR. Sorry for the inconvenience.

2022-09-29 06:47 UTC, closed without merging