Add MutexType to EditorEntityContextRequests
o3de/o3de pull request #12460
Opened 2022-10-06 09:19 UTC by amzn-rhhong

Fixes https://github.com/o3de/o3de/issues/12414
It was discovered that making call to EditorEntityContextRequests is not thread safe. Not sure why it would only be triggered in the repro steps in 12414, but I think it's a reasonable request to add the mutex type to EditorEntityContextRequests Bus.

2022-10-06 13:57 UTC, AMZN-stankowi approved these changes
It would be great to see a regression test written around this, but that's a pretty big ask and could just be backlogged for now.

2022-10-06 14:19 UTC, mbalfour-amzn requested changes
In looking at this bus I would think the vast majority of the methods on it aren't safe to call from another thread, regardless of the EBus mutex (AddEditorEntity, CreateEditorEntity, DestroyEditorEntity, etc). It seems like adding the mutex will just hide other problems.

Either the code that's calling this bus from another thread should be examined and fixed, or if that code is actually calling a method that _is_ safe to call from another thrad, then the methods that are safe to be used from multiple threads (if any) should get split into a separate bus and _that_ bus could have the mutex.

2022-10-06 15:44 UTC, lumberyard-employee-dm commented
Looking at the callstack in issue https://github.com/o3de/o3de/issues/12414 the crash is occurring because of an assert that is called in a function that is not not mutating the state of the EditorEntityContextComponent on multiple threads .
The [EditorEntityContextRequests::GetEditorEntityContextId](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h#L360-L367) function is technically safe to call on multiple threads, but because the call is through an EBus without a mutex and it is happening on multiple threads an assert is occurring.

The mutex is unnecessary for correctness purpose and it is only appeasing the EBus assert check

2022-10-06 22:06 UTC, lumberyard-employee-dm approved these changes

2022-10-06 22:06 UTC, lumberyard-employee-dm commented on Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h
> +        static const bool LocklessDispatch = true;
nitpick: this can be make constexpr
```suggestion
        static constexpr bool LocklessDispatch = true;
```

2022-10-07 10:34 UTC, hultonha approved these changes
Thanks for the info @lumberyard-employee-dm, update by @amzn-rhhong looks good to me 👍

2022-10-11 13:59 UTC, mbalfour-amzn approved these changes
I'm still not fond of this solution, but thank you for adding comments to make it more clear that usage of this bus from other threads is at your own risk.

2022-10-11 13:59 UTC, mbalfour-amzn commented on Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h
> +        // with function like AddEntity, DestroyEntity - those might not be thread safe due the implementation.
Nits: 
"with function" -> "with functions"
"due" -> "due to"

2022-10-13 00:55 UTC, merged