New detail panel for the Asset Browser
o3de/o3de pull request #13793
Opened 2022-12-20 17:59 UTC by ablepharus

Implement a new DockWidget which displays a preview and potentially more information about an asset which gets selected in the Asset Browser

Fixes: #12856

Signed-off-by: Alexander Busse <alex@busse.earth>

## What does this PR do?

Implement a new DockWidget which displays a preview and potentially more information about an asset which gets selected in the Asset Browser

## How was this PR tested?

Manually

2022-12-20 18:20 UTC, ablepharus commented
[13793-asset-browser-details.webm](https://user-images.githubusercontent.com/57981/208738334-2b342440-f2bc-4dbd-b018-1bd3bf1eddff.webm)

2022-12-21 13:18 UTC, MiKom requested changes

2022-12-21 13:18 UTC, MiKom commented on Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
> +        AssetBrowser/AssetBrowserEntityInspectorWidget.h
nit: inconsistent whitespace

2022-12-21 13:18 UTC, MiKom commented on Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
> +            m_previewerFrame->Display(selectedEntry);
It seems that `PreviewerFrame::Display` doesn't do checks for null inside. The chain of calls that happens inside (`PreviewerRequests::GetPreviewerFactory` → `EditorCommonFeaturesSystemComponent::GetPreviewerFactory` → `SharedPreviewerFactory::IsEntrySupported`) may result in calling `GetThumbnailKey` on a null entry. I'd check for nullptr here, and clear if nullptr is indeed passed. Also I suggest documenting this behavior in the header file.

2022-12-21 17:04 UTC, MiKom approved these changes

2022-12-21 17:19 UTC, dtamkin1 approved these changes

2022-12-29 12:08 UTC, MiKom approved these changes

2022-12-29 13:49 UTC, AMZN-daimini commented
```

[2022-12-26T11:33:16.762Z] =========================== short test summary info ===========================

[2022-12-26T11:33:16.762Z] FAILED ..\..\..\..\..\..\AutomatedTesting\Gem\PythonTests\largeworlds\dyn_veg\TestSuite_Main.py::TestAutomation::test_PrefabInstanceSpawner_Embedded_E2E_Editor[windows-AutomatedTesting-windows_editor] - Failed: Test test_PrefabInstanceSpawner_Embedded_E2E_Editor:

[2022-12-26T11:33:16.762Z] Test CRASHED, return code 0xc0000005
```

2022-12-29 14:38 UTC, mbalfour-amzn commented
> ```
> [2022-12-26T11:33:16.762Z] =========================== short test summary info ===========================
> [2022-12-26T11:33:16.762Z] FAILED ..\..\..\..\..\..\AutomatedTesting\Gem\PythonTests\largeworlds\dyn_veg\TestSuite_Main.py::TestAutomation::test_PrefabInstanceSpawner_Embedded_E2E_Editor[windows-AutomatedTesting-windows_editor] - Failed: Test test_PrefabInstanceSpawner_Embedded_E2E_Editor:
> [2022-12-26T11:33:16.762Z] Test CRASHED, return code 0xc0000005
> ```
> 
> Started a new run to see if it was just a sporadic failure

Looks like it might be this failure: https://github.com/o3de/o3de/issues/13115

2023-01-02 10:36 UTC, MiKom approved these changes

2023-01-03 16:48 UTC, lsemp3d approved these changes

2023-01-03 16:49 UTC, merged

2023-01-03 16:52 UTC, cgalvan commented
@ablepharus @rainbj Should this new Asset Browser Inspector be added to the default layout?

2023-01-03 22:34 UTC, dtamkin1 commented
Note, this PR was reverted in #13877 since it caused AR to fail once it was merged