Fix the height of the polygon light will be reset to 0 if other parameters are modified
o3de/o3de pull request #14455
Opened 2023-02-08 02:11 UTC by Zhang-Baochong

Signed-off-by: Zhang-Baochong <zhangbaochong@huawei.com>

## What does this PR do?
 The parameter Height for the Polygon light is set to 0 improperly when operating any other parameter.
Fix : #5541

## How was this PR tested?
Manually tested in editor.
1.Open Editor.
2.Create a new Entity.
3.Add `Light` Component.
4.Select `Polygon` as Light type.
5.Change the Height value.
6.Change any other parameter on the Light panel, the Height value set previously is unchanged.

2023-02-08 06:26 UTC, Jackie9527 approved these changes
lgtm

2023-02-08 18:44 UTC, cgalvan approved these changes

2023-02-08 19:26 UTC, invertednormal commented
This behavior is intentional. The polygon prism shape allows you to create 3d extrusions of polygons, but for the polygon light, extruding the polygon doesn't make sense since the light is only 2d. What problem does this actually solve - is there a bug dealing with the height? is it just confusing that you can set the height to a non-zero value only to have it changed back to zero? Maybe we need to add the ability for the polygon light to disable the height field?

2023-02-08 19:30 UTC, invertednormal commented
Sorry, just noticed the bug link. I think the real issue is UX - it shouldn't be possible to extrude the polygon when its used for polygon lights because the polygon light is 2d. I commented on the bug.

2023-02-08 19:34 UTC, invertednormal requested changes
The polygon height should stay at 0 when used in a polygon light. For a better UX fix, we should open up the ability for the polygon shape component to exist in a 2d-only mode with height disabled or completely hidden.

2023-02-08 19:54 UTC, invertednormal commented
I created a new bug for the UX issue here - #14472

2023-02-09 00:55 UTC, Zhang-Baochong commented
> The polygon height should stay at 0 when used in a polygon light. For a better UX fix, we should open up the ability for the polygon shape component to exist in a 2d-only mode with height disabled or completely hidden.

So #5931 #6127 may be not a bug too?

2023-02-09 20:09 UTC, invertednormal commented
> > The polygon height should stay at 0 when used in a polygon light. For a better UX fix, we should open up the ability for the polygon shape component to exist in a 2d-only mode with height disabled or completely hidden.
> 
> So #5931 #6127 may be not a bug too?

Correct - I'll close both of those and refer them to the UX issue. Thanks for bringing those to my attention.

2023-03-01 01:26 UTC, closed without merging