TIAF: Native test opt-in phase 3
o3de/o3de pull request #15477
Opened 2023-03-30 10:19 UTC by jonawals

## What does this PR do?

This PR opts in the phase 3 native tests for TIAF.

## How was this PR tested?

This PR will be tested in AR.

2023-03-30 17:04 UTC, lumberyard-employee-dm requested changes

2023-03-30 17:04 UTC, lumberyard-employee-dm commented on Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/CMakeLists.txt
> +
Nothing was changed in this file.

2023-03-31 16:39 UTC, jonawals commented on Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/CMakeLists.txt
> +
Fixed, unblock the PR ASAP please.

2023-03-31 16:41 UTC, lumberyard-employee-dm requested changes

2023-03-31 16:41 UTC, lumberyard-employee-dm commented on Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/CMakeLists.txt
> +        LABESL REQUIRES_tiaf
There is a typo in `LABEL` here
```suggestion
        LABEL REQUIRES_tiaf
```

2023-03-31 16:42 UTC, lumberyard-employee-dm commented on Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/CMakeLists.txt
> +
This is not fixed.

2023-03-31 16:43 UTC, lumberyard-employee-dm approved these changes

2023-03-31 17:34 UTC, merged