fix misc project bugs in Project Manager
o3de/o3de pull request #15474
Opened 2023-03-30 00:49 UTC by AMZN-alexpete

## What does this PR do?

- fixes https://github.com/o3de/o3de/issues/15360
- fixes https://github.com/o3de/o3de/issues/12901
- fixes issue where users could not add projects with compatibility warnings
- fixes issue where adding a project didn't register it to the specific engine in use.  If the user had multiple engines with the same name, the project just used the most compatible engine name, which may not be the engine in use.
- fixes missing error and success messages when adding a project
![image](https://user-images.githubusercontent.com/26804013/228699652-505a1196-8344-490e-871a-43239c86c5b1.png)

![image](https://user-images.githubusercontent.com/26804013/228699793-b371903e-4df0-4d0b-bf0d-c3d78f4d7fe1.png)

I'm debating if we should add the specifier that registers the project to a specific engine version e.g. o3de~=2.0.0, which could be an issue for any project that being used with the development branch of the engine which may have frequent engine version changes.

## How was this PR tested?

- ran o3de pytests
- tested adding and removing projects that had invalid project.json files, missing project.json files, and specified incompatible engines
- tested adding multiple projects with the same name and different versions
- verified updates to the local user's project.json `engine_path` existed in the project folder after adding it

2023-03-30 00:57 UTC, lumberyard-employee-dm commented
> I'm debating if we should add the specifier that registers the project to a specific engine version e.g. o3de~=2.0.0, because I don't want users working with a development engine to have to keep registering their project (or edit the project.json to remove the specifier), but it could be really useful for anyone using a release engine. So, I might make this change in a later PR that involves showing engine compatibility in the project properties UI

This should be determined by the user. There is no way to handle the users "wants" here by making a decision on their behalf.

2023-03-30 01:16 UTC, lumberyard-employee-dm requested changes

2023-03-30 01:21 UTC, lumberyard-employee-dm commented on Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
> +        connect(reinterpret_cast<ScreensCtrl*>(parent), &ScreensCtrl::NotifyProjectRemoved, m_projectGemCatalogScreen, &GemCatalogScreen::NotifyProjectRemoved);
repeat: This needs to be a `static_cast`
```suggestion
        connect(static_cast<ScreensCtrl*>(parent), &ScreensCtrl::NotifyProjectRemoved, m_projectGemCatalogScreen, &GemCatalogScreen::NotifyProjectRemoved);
```

2023-04-08 00:30 UTC, lumberyard-employee-dm approved these changes

2023-04-10 23:25 UTC, tkothadev approved these changes

2023-04-12 16:28 UTC, merged