Adding default value to enabled flag on DrawItem
o3de/o3de pull request #17024
Opened 2023-11-07 21:19 UTC by antonmic

Will fix https://github.com/o3de/o3de/issues/17018

2023-11-07 21:21 UTC, galibzon approved these changes

2023-11-07 21:26 UTC, moudgils approved these changes

2023-11-07 21:38 UTC, AMZN-Gene approved these changes

2023-11-07 21:40 UTC, VickyAtAZ commented on Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h
> +            uint8_t m_allFlags = 1;
I think it's better to add m_enabled = true in constructor if `bool m_enabled : 1 = 1;` is not supported.
The union was added to have the potential of more than one flags. 
The m_allFlags = 1; here you have is to intent to set m_enabled = true which is implicit. 
If people add a flag before m_enabled in the future which could easily break the intention.

2023-11-07 21:48 UTC, AMZN-Gene approved these changes

2023-11-07 21:48 UTC, AMZN-Gene commented on Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h
>                  bool m_enabled : 1;    // Whether the Draw Item should render
Suggest adding a comment about the union being created to support any number of user flags (as long as they fit within 8bit), but current use only uses a 1-bit bitfield to determine if the draw item is enabled or not.

2023-11-08 19:26 UTC, VickyAtAZ requested changes
Please check my comment.

2023-11-08 21:18 UTC, VickyAtAZ commented on Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h
> +            uint8_t m_allFlags = 1;
Another option would be use m_disabled and set m_allFlags = 0; by default

2023-11-09 00:33 UTC, VickyAtAZ approved these changes

2023-11-09 00:42 UTC, merged