Fix DPE component adapter to respect attributes when requested
o3de/o3de pull request #17152
Opened 2023-11-30 21:29 UTC by gadams3

## What does this PR do?

Noticed that the DPE was not updating previews while using the material component instance inspector. The preview images were not updating in response to changing colors and other properties. This is controlled by invalidating the property editor and sending image data via an attribute that gets applied to an icon on the property asset control. 

The adapter only has three refresh levels, none, soft, and hard, compared to the RPE which has a few more. The adapter was only performing a soft refresh whenever invalidation was requested. Hard refresh is required to update attributes.

This should also impact other components and property editors that have dynamic attributes

## How was this PR tested?

Before the changes, the property asset control never received the new attributes.
After the changes, the property asset control receives the updated attributes and updates the image.

2023-12-01 04:16 UTC, lsemp3d approved these changes

2023-12-01 16:08 UTC, alexmontAmazon requested changes
I've discussed this with @gadams3 offline, this change shouldn't theoretically be necessary, if all the necessary attributes are exposed to the DPE. We'll work together on that solution.

2024-03-19 20:59 UTC, AMZN-daimini approved these changes

2024-03-19 21:00 UTC, AMZN-daimini commented
> I've discussed this with @gadams3 offline, this change shouldn't theoretically be necessary, if all the necessary attributes are exposed to the DPE. We'll work together on that solution.

Closing as per this comment

2024-03-19 21:00 UTC, closed without merging