feature: improve assertions for RHI Vulkan result
o3de/o3de pull request #17169
Opened 2023-12-03 02:30 UTC by pollend

## What does this PR do?

`AssertSuccess` wraps an assertion for a given line but the asserted code is in a nested call. this just moves the assertion to a macro so the inlined call will be correctly reflected in the logs. 

```
==================================================================
System: Trace::Assert
 /home/michaelpollind/projects/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp(336): (139819752497152) 'virtual RHI::ResultCode AZ::Vulkan::Device::InitInternal(RHI::PhysicalDevice &)'
System: ASSERT: Vulkan API method failed: Feature not present
```

2023-12-04 06:12 UTC, moudgils approved these changes

2023-12-04 14:23 UTC, akioCL requested changes

2023-12-04 19:26 UTC, gadams3 approved these changes

2023-12-04 20:12 UTC, akioCL approved these changes

2024-02-22 06:17 UTC, pollend commented
> Need to merge or rebase against development for build fixes

been a bit slow I rebased this branch to development.

2024-03-22 17:51 UTC, gadams3 commented
Please check Jenkins to address Linux build failures.

e3e2334e/Code/CMakeFiles/Atom_RHI_Vulkan.Private.Static.dir/profile/Source/RHI/Fence.cpp.o -c /data/workspace/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.cpp
11:46:18  /data/workspace/o3de/Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.cpp:89:17: error: use of undeclared identifier 'AssertSuccess'
11:46:18                  AssertSuccess(result);
11:46:18                  ^

2024-03-22 21:28 UTC, pollend commented
sounds good, looks like this changed quite a lot since I looked at this.

2024-06-27 16:23 UTC, nick-l-o3de commented
Unfortunately, it looks like things changed to cause conflicts

2025-08-10 03:43 UTC, moudgils commented
@pollend - Please go ahead merge to the latest and merge as this PR has the approvals.

2025-08-19 05:45 UTC, pollend commented
I haven't touched this project in over a year struggling a little with compiling.

any clue with this build error.
```
>>> referenced by MockFileIOBase.h:81 (/home//projects/o3de/Code/Framework/AzCore/./AzCore/UnitTest/Mocks/MockFileIOBase.h:81)
>>>               Code/Tools/AssetProcessor/CMakeFiles/AssetProcessor.Tests.dir/debug/native/tests/UnitTestUtilities.cpp.o:(AZ::IO::MockFileIOBase::InstallDefaultReturns(testing::NiceMock<AZ::IO::MockFileIOBase>&))
clang++-19: error: linker command failed with exit code 1 (use -v to see invocation)
```

2025-10-16 12:34 UTC, jhmueller-huawei commented on Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
> +            vkResult = device.GetContext().GetPhysicalDeviceSurfacePresentModesKHR(
This variable hasn't been declared so this cannot be built.

2025-10-24 05:52 UTC, jhmueller-huawei commented
Still fails with an undeclared variable error, another variable this time. Please try compiling it locally.

2025-10-24 14:43 UTC, pollend commented
looks like I missed a couple cases in the AR.

2025-10-25 22:38 UTC, pollend commented
The errors left in AR seem unrelated.

2026-07-13 16:02 UTC, nick-l-o3de approved these changes

2026-07-13 16:04 UTC, merged