Fix for python bindings on Linux for methods that return size_t
o3de/o3de pull request #17753
Opened 2024-04-16 22:09 UTC by spham-amzn

## What does this PR do?
Fixes https://github.com/o3de/o3de/issues/17692 

## Root Cause
For python scripts that invokes methods that return `size_t`, the RTTI type reported by [BehaviorMethod](https://github.com/o3de/o3de/blob/cc6f9f36df4ba97a31e07a26ed9b975c2df891a0/Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h#L298) is different for method signatures on Windows vs. Linux. On Windows, the return  RTTI type resolves to `AZ::u64`, but on Linux, the RTTI type resolves to `unsigned long`. 

So when the [ShaderManagementConsoleDocumentRequests](https://github.com/o3de/o3de/blob/cc6f9f36df4ba97a31e07a26ed9b975c2df891a0/Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h#L29) is registered, the method [GetShaderOptionDescriptorCount](https://github.com/o3de/o3de/blob/cc6f9f36df4ba97a31e07a26ed9b975c2df891a0/Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h#L75) is reported with a return type of `AZ::u64` on Windows, and `unsigned long` on Linux. 

The problem occurs when [AllocateBehaviorValueParameter](https://github.com/o3de/o3de/blob/cc6f9f36df4ba97a31e07a26ed9b975c2df891a0/Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp#L281) is invoked during the invocation of the python script [ExpandOptionsFullCombinatorials.py](https://github.com/o3de/o3de/blob/development/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py), it does not recognize that `unsigned long` is not a [primitive type](https://github.com/o3de/o3de/blob/cc6f9f36df4ba97a31e07a26ed9b975c2df891a0/Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp#L303-L307).

## Resolution
To handle the situation where the python bindings are invoked that has `size_t` as the return type, we will add the missing `long` and `unsigned long` in the [IsPrimitiveType](https://github.com/o3de/o3de/blob/cc6f9f36df4ba97a31e07a26ed9b975c2df891a0/Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp#L223) method.

## How was this PR tested?
Ran the steps detailed in https://github.com/o3de/o3de/issues/17692

2024-04-16 23:06 UTC, AMZN-Gene approved these changes

2024-04-17 09:36 UTC, AMZN-daimini approved these changes

2024-04-17 15:22 UTC, lemonade-dm requested changes

2024-04-17 15:22 UTC, lemonade-dm commented on Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
> +                        ConvertBehaviorParameterEnum<unsigned short>(obj, underlyingTypeId, parameter) ||
`short` and `unsigned short` are covered by `AZ::s16` and `AZ::u16` respectively as they are always the same type.
Only `long` and `unsigned long` needs to be covered

2024-04-17 15:22 UTC, lemonade-dm commented on Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
> +                    ConvertPythonFromEnumClass<unsigned short>(underlyingTypeId, behaviorValue, outboundPythonValue) ||
The short` and `unsigned short` type is covered by the `AZ::s16` and `AZ::u16` type aliases as they are always the `short` type.

2024-04-17 15:22 UTC, lemonade-dm commented on Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
> +                    AZ::AzTypeInfo<short>::Uuid() == typeId || AZ::AzTypeInfo<unsigned short>::Uuid() == typeId ||
repeat: The check for `short` and `unsigned short` should be removed as they are already being checked via `AZ::s16` and `AZ::u16`.

2024-04-17 16:32 UTC, lemonade-dm approved these changes

2024-04-17 17:47 UTC, merged