Request the timeline semaphore extension for Vulkan <1.2
o3de/o3de pull request #17766
Opened 2024-04-18 09:31 UTC by msat-huawei

## What does this PR do?

This resolves a problem with timeline semaphores on devices with Vulkan <1.2.
The solution was proposed by @akioCL on the sig-graphics-audio [Discord](https://discord.com/channels/805939474655346758/816043793576886273/1228019420237135945) in a discussion with @galibzon

## How was this PR tested?

I only have access to devices with Vulkan versions >=1.2, so I could not actually test this.

2024-04-18 09:36 UTC, jhmueller-huawei requested changes

2024-04-18 09:36 UTC, jhmueller-huawei commented on Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
> +            auto timelineSemaphore = physicalDevice.GetPhysicalDeviceTimelineSemaphoreFeatures();
This line separates the comments above from the `if` that they document. Please move the line further up.

2024-04-19 07:25 UTC, jhmueller-huawei approved these changes

2024-04-29 06:13 UTC, jhmueller-huawei commented
@galibzon Does this PR fix the issue for you on Android? We cannot really test it with only machines that have at least Vulkan 1.2.

2024-04-29 17:01 UTC, galibzon commented
> @galibzon Does this PR fix the issue for you on Android? We cannot really test it with only machines that have at least Vulkan 1.2.

Yes, the code in the PR is correct. Still there's another BUG that occurs on Quest devices . See my PR where I'm doing the same you are doing , plus the addition of a new C++ macro, plus CMake hackery to fully disable timeline semaphores. https://github.com/o3de/o3de/pull/17721

2024-04-30 06:25 UTC, merged