Show pass execution device index if multi devices are available
o3de/o3de pull request #17904
Opened 2024-05-11 02:38 UTC by hosea1008

## What does this PR do?

This PR shows the device index if there are multiple devices available

## How was this PR tested?

Self tested on windows with one and two devices.

2024-05-11 06:53 UTC, martinwinter-huawei approved these changes

2024-05-13 08:12 UTC, jhmueller-huawei requested changes

2024-05-13 08:12 UTC, jhmueller-huawei commented on Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
> +                    ImGui::Text("Pass run on device %d", AZStd::max(asRenderPass->GetDeviceIndex(), 0));
Minor grammar fix: "Pass runs on device %d".

2024-05-13 19:48 UTC, moudgils approved these changes

2024-05-14 12:08 UTC, jhmueller-huawei approved these changes

2024-05-17 07:43 UTC, merged