DX12: Remove name from FenceEvent windows event
o3de/o3de pull request #18097
Opened 2024-07-08 13:27 UTC by msat-huawei

## What does this PR do?

This fixes a problem when we wait for more than one fence at the same time.

According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa), there cannot be two different events with the same name. Creating the second event returns the first one again:

```
If the named event object existed before the function call, the function returns a handle to the existing object and [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror) returns ERROR_ALREADY_EXISTS.
```

We therefor had only one event for two fences, sometimes leading to the problem that the wrong thread continued.

## How was this PR tested?

AtomSampleViewer on Windows+DX12. The Multi GPU RPI sample with the Copy Test Pipeline led to a deadlock with DX12. This PR fixes that problem.

2024-07-08 13:30 UTC, jhmueller-huawei requested changes
Can we remove the name altogether then? :)

2024-07-08 13:36 UTC, msat-huawei commented
I removed the conversion to `wstring`. The name is still used for the profile scope name though.

2024-07-08 13:36 UTC, jhmueller-huawei approved these changes

2024-07-09 12:41 UTC, martinwinter-huawei approved these changes

2024-07-09 12:44 UTC, merged