Add option to set a default buffer/image view for transient buffer/image attachments
o3de/o3de pull request #18221
Opened 2024-08-13 15:20 UTC by mprettner-huawei

## What does this PR do?

This PR adds the option to define a default buffer view for transient image and buffer attachments, such that a buffer/image view does not need to be defined when the attachment is used in a slot in a different pass and the default view is sufficient. This is especially useful when defining the size of a transient buffer in c++ in `BuildInternal()` (eg. when using a constant from c++ as the buffer size) of a pass class, and then using the same attachment in multiple different passes. Without this change, each pass who uses the attachment would need to update its buffer view separately. With this change, only the buffer declaration needs to be updated.
An alternative would of course be to use an imported buffer/image, but this would also require additional code to manage the resource and its lifetime.

For example, if I wanted to make a buffer of some structs of size 16 bytes I would use this code:
```
"PassRequests": [
	...
	"BufferAttachments": [
		{
			"Name": "Buffer1",
			"BufferDescriptor": {
				"m_bindFlags": "ShaderReadWrite",
				"m_byteCount": "1024",
				"m_alignment": "16"
			},
			"BufferViewDescriptor": {
				"m_elementSize": 16
			}
		}
	]

-- Somewhere else --

"PassTemplate": {
	...
	"Slots": [
		{
			"Name": "Buffer1",
			"ShaderInputName": "m_buffer1",
			"SlotType": "InputOutput",
			"ScopeAttachmentUsage": "Shader"
			// Dont need to add "BufferViewDesc" here
		}
	]
```

## How was this PR tested?

As far as I can tell there is no active code in a engine build with a default project template which uses the `"BufferViewDesc"` option when defining a slot, so I cannot submit any .pass-file changes together with this PR. I tested these changes with an internal gem which makes heavy use of compute shaders, and there I was able to remove various instances of defining the same `"BufferViewDesc"` for slots over and over again.

2024-08-14 07:03 UTC, jhmueller-huawei requested changes

2024-08-14 07:03 UTC, jhmueller-huawei commented on Gems/Atom/RHI/Code/Source/RHI.Reflect/UnifiedAttachmentViewDescriptor.cpp
> +        : m_type{ AttachmentType::Buffer }
err

2024-08-14 07:03 UTC, jhmueller-huawei commented on Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/UnifiedAttachmentViewDescriptor.h
> +        AttachmentType m_type{ AttachmentType::Uninitialized };
This is unused currently, but I see, why you would keep it.

2024-08-14 07:50 UTC, jhmueller-huawei approved these changes

2024-08-14 08:02 UTC, jhmueller-huawei approved these changes

2024-08-15 15:17 UTC, moudgils approved these changes

2024-08-15 18:54 UTC, antonmic approved these changes
Great changes, thanks for adding this!

2024-08-16 07:38 UTC, merged