Extend pass attachment binding count
o3de/o3de pull request #18335
Opened 2024-09-24 12:21 UTC by hosea1008

## What does this PR do?

The current pass attachment binding count is set to 32, for some parent pass that has multiple complex children, this limit can be easily exceeded.

This PR increase this limit further to 48,  not adding too much performance but might be sufficient for most of the use cases.

## How was this PR tested?

Tested in windows

2024-09-25 06:00 UTC, msat-huawei commented
I think we should add something like boosts [small_vector](https://www.boost.org/doc/libs/1_85_0/doc/html/boost/container/small_vector.html) or LLVMs [SmallVector](https://llvm.org/doxygen/classllvm_1_1SmallVector.html) instead of increasing the size of the attachment binding vector every time we have a pass that needs lots of attachments. This way most pass attachment vectors would still be on the stack, while also allowing passes with lots of attachments.

I'm not sure if the licenses are compatible, or what the process is of getting 3rd party code into O3DE is. So just adapting these for O3DEs needs might not be that easy.

2024-09-25 06:48 UTC, jhmueller-huawei commented
That doesn't work unfortunately as the code depends on the elements staying where they are, i.e., pointers to the elements are used.

2024-09-27 20:20 UTC, moudgils approved these changes

2024-09-27 20:23 UTC, moudgils commented
Updating to boost libs is more of a foundational question and probably not recommended. Ideally you want to stick to data structures defined within AZCore but we have added additional data structures to AtomCore as the bar is much higher within AZCore. Ideally you would want to move everything from AtomCore to AZCore but that is 'nice to have' at this point.

2024-09-30 07:30 UTC, jhmueller-huawei commented
There are 4 `fixed_vector`s in the `Pass` class that are affected by this value: `m_attachmentBindings`, `m_inputBindingIndices`, `m_inputOutputBindingIndices` and `m_outputBindingIndices`. I think at this point where we would increase their size to 48, we should consider just using normal `vector`s.

The most critical of these four is `m_attachmentBindings` where the comment states that fixed size is used for performance as it's possible to hold pointers to the bindings for connections. If we make this a `vector` of intrusive pointers we can still do that, so the impact on performance should be negligible and then the number of bindings is not limited anymore. I think the impact of this change on performance should be negligible. What do you think about that @moudgils ?

2024-10-08 03:00 UTC, hosea1008 commented
> There are 4 `fixed_vector`s in the `Pass` class that are affected by this value: `m_attachmentBindings`, `m_inputBindingIndices`, `m_inputOutputBindingIndices` and `m_outputBindingIndices`. I think at this point where we would increase their size to 48, we should consider just using normal `vector`s.
> 
> The most critical of these four is `m_attachmentBindings` where the comment states that fixed size is used for performance as it's possible to hold pointers to the bindings for connections. If we make this a `vector` of intrusive pointers we can still do that, so the impact on performance should be negligible and then the number of bindings is not limited anymore. I think the impact of this change on performance should be negligible. What do you think about that @moudgils ?

That would make it a very impactful change since a lot of places are accessing the bindings via member accessor `.`, we would have to replace them to `->`, which would impact almost all the Gems.

I personally prefer doing it in another PR or start a discussion before doing that. Do we really need unlimited binding count?

2024-10-09 16:35 UTC, moudgils commented
I am supportive of switching to 'vector' and switching to intrusive pointers as I dont expect re-allocations to happen once the render pipeline is loaded. If we switch pipelines or enable/disable features at runtime a re-allocation can happen but that should be rare in a gamelauncher and is more of an editor/debugging feature. Tagging in @antonmic if he has any concerns.

2024-10-10 12:50 UTC, kh-huawei commented
Can i suggest `AZStd::deque` with a sufficiently large `NumElementsPerBlock`? It allocates multiple chunks of contiguous memory, provides random access iterators, and adding / removing elements does not invalidate references to existing members.

By default a deque limits the chunk-size to 16 byte though (or one element per chunk, if the element is larger), so to get any benefit we would need to configure this better.

2024-10-10 13:47 UTC, jhmueller-huawei commented
> As @jhmueller-huawei mentioned, the code setup relies on the bindings not moving around in memory. The intrusive pointers could work functionality wise but then you have passes touching bindings that are scattered in memory and hurting cache efficiency (part of the reason this is a fixed vector is so all the bindings are with the pass in memory).

How much impact does that actually have on performance? Considering that intrusive pointers are used pretty much everywhere else I thought that should be really minor.

2024-10-11 17:47 UTC, moudgils commented
Do we even need to switch to  intrusive pointers? Can simply changing to vector not suffice?

2024-10-12 01:06 UTC, hosea1008 commented
I managed to get rid of the many bindings by using PipelineGlobal, but considering the PipelineGlobal might not be that friendly to multi-device use case, if we can change the fixed_vector to vector with acceptable minor performance loss, I am happy to make that change.

Probably if we create a vector with pre-set reserved capacity, it would not going to allocate new memory that frequently, and considering the pipeline/binding changes will only happen on edit time, I personally vote that changing it to conventional vector is not that impactful to the performance and user experience.

2024-10-12 08:28 UTC, hosea1008 commented
> As @jhmueller-huawei mentioned, the code setup relies on the bindings not moving around in memory. The intrusive pointers could work functionality wise but then you have passes touching bindings that are scattered in memory and hurting cache efficiency (part of the reason this is a fixed vector is so all the bindings are with the pass in memory). Don't see a clear solution at the moment but I would like to know more about the use case where 32 bindings on a pass is not enough, it sounds like a painful workflow to have to create that many slots and manage all the connections from parents to children. Is it possible for you to share the passes that are raising this issue? There are pipeline global connections (search for PipelineGlobal in the code) that allow you to declare certain attachments as global so that you can access them anywhere (like the depth buffer), this let's you avoid having to pass every attachment down through parent -> child passes and access global declared attachments directly.

My pass is a pass wrapping a shading pass (similar to the OpaqueParent pass in MainPipeline), but my shading pass is more complicated so it has more required inputs (the current ForwardPass already has 14 slots). 

PipelineGlobal is a potential way, but some of my pass's input come from some optionally inserted passes, making the  registration/connection to pipeline global more complicated. Considering the PipelineGlobal might not be that friendly to multi-device use cases, in the latest commit I am trying to change the fixed_vector to vector and reserve the memory in the Pass constructor.

I think maybe if we create a vector with pre-set reserved capacity, it would not going to allocate new memory that frequently, and considering the pipeline/binding changes will only happen on edit time, I personally vote that changing it to conventional vector is not that impactful to the performance and user experience.

2024-10-14 14:34 UTC, jhmueller-huawei commented
> Do we even need to switch to intrusive pointers? Can simply changing to vector not suffice?

The issue with using just a vector is that as you add more (than the reserved) amount of pass attachment bindings, it needs to reallocate. This means that at this point any raw pointers in the `m_connectedBinding` member of a pass attachment binding that refers to one of the reallocated and thus moved bindings will not point to the correct memory anymore.

As long as all `Pass::AddAttachmentBinding` calls happen for a pass A before any `m_connectedBinding` pointers get set, pointing to pass A's bindings that is fine, as that's the only method where pass attachment bindings are pushed into the vector.

Currently, I think that all calls (to `AddAttachmentBinding` and also most of the times when `m_connectedBinding` is set) happen in the Build phase of a pass. As far as I can tell, as long as the order is correct that doesn't cause issues at the moment. But I am not 100 % sure and there is no check if this issue happens.

Maybe we should at least add a mechanism to check if that happens. E.g. set a flag in a pass as soon as an `m_connectedBinding` refers to that pass and assert/warn/error when that flag is set when `AddAttachmentBinding` is called.

2024-10-17 00:59 UTC, antonmic requested changes
These latest changes should crash for your use case:
The limit remains the same at 32
You reserve the size of the vectors at 32
When you exceed this size in your use case, the vector will grow and move existing bindings in memory
Pointers to those bindings become stale and should cause bad things to happen.

Have you run your pipeline successfully without any major issues? If so I'm quite curious why it doesn't crash. Maybe it's as @jhmueller-huawei mentioned, the build steps between passes are all in the right order and the pointers are created after the vector is already filled.

2024-10-21 01:27 UTC, hosea1008 commented
> These latest changes should crash for your use case: The limit remains the same at 32 You reserve the size of the vectors at 32 When you exceed this size in your use case, the vector will grow and move existing bindings in memory Pointers to those bindings become stale and should cause bad things to happen.
> 
> Have you run your pipeline successfully without any major issues? If so I'm quite curious why it doesn't crash. Maybe it's as @jhmueller-huawei mentioned, the build steps between passes are all in the right order and the pointers are created after the vector is already filled.

Yes, I tried, it works maybe because the build steps currently happen to meet the required order. I am aware of the memory-reallocation issue. Gonna fix it.

2024-10-31 14:24 UTC, jhmueller-huawei commented
I have described in #18438 what the issue is, why a deque doesn't work at the moment. A workaround when using a deque would be to just not clear it and instead store the number of elements that are currently used. I have a patch that works like this, if we should go for it, but it's a dirty hack of course. What do you think?

2025-02-06 06:59 UTC, hosea1008 commented
> I have described in #18438 what the issue is, why a deque doesn't work at the moment. A workaround when using a deque would be to just not clear it and instead store the number of elements that are currently used. I have a patch that works like this, if we should go for it, but it's a dirty hack of course. What do you think?

What was the patch? Since the issue seems not able to collect ideas and fixes, I think either extending the attachment binding count or using your patch is worthy for a try.

2025-02-07 14:20 UTC, jhmueller-huawei commented
> > I have described in #18438 what the issue is, why a deque doesn't work at the moment. A workaround when using a deque would be to just not clear it and instead store the number of elements that are currently used. I have a patch that works like this, if we should go for it, but it's a dirty hack of course. What do you think?
> 
> What was the patch? Since the issue seems not able to collect ideas and fixes, I think either extending the attachment binding count or using your patch is worthy for a try.

I created a PR for it: #18673

2025-02-19 07:39 UTC, jhmueller-huawei commented
Closing this since #18673 has been merged.

2025-02-19 07:39 UTC, closed without merging