Add interface to expose members that not necessarily keep private
o3de/o3de pull request #18333
Opened 2024-09-24 07:02 UTC by hosea1008

## What does this PR do?

This PR adds interface to `RayTracingFeatureProcessor` and `MeshFeatureProcessor` to access some of the members that are necessary for Gems to implement some features that need to scan over ray tracing meshes.

## How was this PR tested?

Tested in Windows

2024-09-24 09:26 UTC, siliconvoodoo commented
just that is enough to actually make changes to the mesh map from the point of view of other code parts, and the results will be as hoped? _(that the raytracer actually takes into account these meshes, by including them in BLAS and their BLASes in the TLAS, and runs the update gpu command)._
Maybe I'd like it if the comment on top of the non-const version of the getter would explain the conditions. Like if you need to run some "finalize" yourself at some point, or if there is a context in which it's too late to make changes.
bests.

2024-09-24 09:41 UTC, hosea1008 commented
> just that is enough to actually make changes to the mesh map from the point of view of other code parts, and the results will be as hoped? _(that the raytracer actually takes into account these meshes, by including them in BLAS and their BLASes in the TLAS, and runs the update gpu command)._ Maybe I'd like it if the comment on top of the non-const version of the getter would explain the conditions. Like if you need to run some "finalize" yourself at some point, or if there is a context in which it's too late to make changes. bests.

Removed the non-const version of GetMeshMap

2024-09-24 11:19 UTC, jhmueller-huawei requested changes

2024-09-24 12:11 UTC, jhmueller-huawei approved these changes

2024-09-27 20:19 UTC, moudgils approved these changes

2024-09-30 07:32 UTC, merged