Skinned mesh fix
o3de/o3de pull request #18426
Opened 2024-10-29 04:33 UTC by HydrogenC

## What does this PR do?
Fix crash when importing an Actor with only blendshape but without skinning. Closes #18381. 
The implementation is made in the following aspects: 
 - Mark `SKIN_JOINTINDICES` and `SKIN_WEIGHTS` as optional so that it won't trigger an error when these streams aren't found. 
 - Add some additional null check and make some asserts only active when there's skinning
 - Add a new skinning method call `NoSkinning` which skips the skinning calculation in the skinning shader. When an Actor doesn't have skin weights, then the skinning method falls back to `NoSkinning` automatically. 

## How was this PR tested?

_Please describe any testing performed._
Tested on windows, both DX12 and Vulkan. It now works well with Actors with only blendshapes, and I suppose that the original functionality won't be affected. 
However, since I am new to O3DE source code, I am not fully aware of how the modules affect each other, so my changes might break other parts potentially. This has to be checked.

2024-10-29 16:29 UTC, moudgils approved these changes
Thanks for this contribution. Looks good. Just make sure to do testing with skinned data to ensure that workflow did not break in any way.

2024-10-29 16:29 UTC, moudgils commented on Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
> +                m_boneTransforms.reset();
Coding standard - Use {}

2024-10-29 16:31 UTC, moudgils requested changes
Actually this PR needs to be going into development branch.

2024-10-29 23:25 UTC, HydrogenC commented
> Thanks for this contribution. Looks good. Just make sure to do testing with skinned data to ensure that workflow did not break in any way.

Thanks. Is there any standard asset(s) to do the test with?

2024-10-30 08:39 UTC, HydrogenC commented
> Actually this PR needs to be going into **development** branch.



> Yeah, please rebase on Development branch Main is the actual release and only updates once whenever a release is made, development is where we target fixes for next release.

I understand. I'll create a new PR for that.

2024-10-30 08:39 UTC, closed without merging