Project Manager: Added Per Project Template Previews and Icon Overlays
o3de/o3de pull request #1994
Opened 2021-07-08 20:31 UTC by AMZN-nggieber

Recreated PR: https://github.com/o3de/o3de/pull/1918 after it got messed up by issues with DCO

Signed-off-by: nggieber <nggieber@amazon.com>
![o3de_AVE10tyttN](https://user-images.githubusercontent.com/52797929/124986603-a5b24180-dff0-11eb-9315-e170d34125cc.png)

2021-07-08 21:02 UTC, AMZN-alexpete requested changes
Rather than putting the icons in the ProjectManager, let's put them in the templates - either bake them into the existing preview images (preferred) or add the .svg there with a name like 'template_icon.svg' etc

2021-07-08 22:42 UTC, amznestebanpapp approved these changes

2021-07-08 22:42 UTC, amznestebanpapp commented on Code/Tools/ProjectManager/Source/TemplateButtonWidget.h
> +        Q_OBJECT // AUTOMOC
the `AUTOMOC` is not needed

2021-07-08 23:17 UTC, AMZN-alexpete approved these changes

2021-07-08 23:18 UTC, AMZN-Phil approved these changes

2021-07-09 00:05 UTC, AMZN-ScottR approved these changes

2021-07-09 15:15 UTC, merged