Added support for pytest marks, including skipping of tests
o3de/o3de pull request #2353
Opened 2021-07-22 15:56 UTC by AMZN-AlexOteiza

2021-07-22 17:10 UTC, evanchia-ly-sdets approved these changes

2021-08-06 12:03 UTC, jonawals approved these changes

2021-08-06 18:20 UTC, Kadino requested changes
Given there is no description, how does this define 'support for marks' on these tests? Anything collected normally should already function. I assume the marks exist in separate test files which are being collected? Is there an example/sanity test which verifies this works?

2021-08-09 22:57 UTC, AMZN-AlexOteiza commented
> Given there is no description, how does this define 'support for marks' on these tests? Anything collected normally should already function. I assume the marks exist in separate test files which are being collected? Is there an example/sanity test which verifies this works?

Since the editor tests are created with the new system, they have custom collectors and the run functions are autogenerated, these functions didn't get the marks before this PR that should get from its spec class.

2021-08-10 08:08 UTC, merged