Made entity aliases more descriptive
o3de/o3de pull request #2629
Opened 2021-07-29 20:52 UTC by AMZN-eameyaw

Signed-off-by: Enoch Ameyaw <eameyaw@amazon.com>

2021-07-30 16:19 UTC, gadams3 requested changes

2021-07-30 16:19 UTC, gadams3 commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
> +            //AZStd::string entityName = AZStd::string::format("Entity%llu", static_cast<AZ::u64>(m_newEntityCounter++));
this commented code should be deleted if it's no longer needed

2021-07-30 16:19 UTC, gadams3 commented on Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
>          }
Instead of abbreviating, spell out the entire variable name, entityName. That also matches the declaration.

2021-07-30 20:58 UTC, gadams3 approved these changes

2021-08-04 16:52 UTC, AMZN-eameyaw commented
Accidently sent this PR to development. The actual PR is here: https://github.com/aws-lumberyard-dev/o3de/commit/cc1e3afe7c9f4133fb8b06e83f065e56fa8d14f2?branch=cc1e3afe7c9f4133fb8b06e83f065e56fa8d14f2&diff=split

2021-08-18 16:39 UTC, closed without merging