Fix Blast Gem Compiler Error
o3de/o3de pull request #3855
Opened 2021-09-01 20:48 UTC by AMZN-Gene

Small fix for compilation
Signed-off-by: Gene Walters <genewalt@amazon.com>

2021-09-01 20:57 UTC, AMZN-Olex approved these changes

2021-09-01 21:16 UTC, amznestebanpapp approved these changes

2021-09-01 21:34 UTC, kberg-amzn approved these changes

2021-09-01 21:34 UTC, AMZN-puvvadar approved these changes

2021-09-02 00:01 UTC, lumberyard-employee-dm requested changes
The include path should be has a case-sensitive typo

2021-09-02 00:01 UTC, lumberyard-employee-dm commented on Gems/Blast/Code/Source/Family/DamageManager.h
> +#include <AZCore/Interface/Interface.h>
The include path has a case-sensitive typo that prevent this from compiling on case-sensitive platforms like Linux

```suggestion
#include <AzCore/Interface/Interface.h>
```

2021-09-02 00:06 UTC, lumberyard-employee-dm approved these changes

2021-09-02 03:46 UTC, merged