Googletest serial option
o3de/o3de pull request #3996
Opened 2021-09-08 18:38 UTC by evanchia-ly-sdets

Enables the serial option for googletests when registering them to CMake. Moved the function to ly_add_test() to simplify

2021-09-08 21:15 UTC, lumberyard-employee-dm reviewed
Well currently all of our Googletest are parallizable and succeeds when run non-serially.

It is the python test that have the issues with running in parallel.

My thoughts are that we should encourage users to continue to author Googletest that can run in parallel.

2021-09-08 23:57 UTC, amznestebanpapp requested changes

2021-09-08 23:57 UTC, amznestebanpapp commented on cmake/LYTestWrappers.cmake
> +        TEST_SERIAL
this will make every test serial, here you should pass `${ly_add_googletest_TEST_SERIAL}` to consume the parameter

2021-09-08 23:57 UTC, amznestebanpapp commented on cmake/LYTestWrappers.cmake
> +        TEST_SERIAL
same here, you should pass `${ly_add_pytest_TEST_SERIAL}` instead

2021-09-08 23:57 UTC, amznestebanpapp commented on cmake/LYTestWrappers.cmake
> +    set(options EXCLUDE_TEST_RUN_TARGET_FROM_IDE TEST_SERIAL)
please add a comment for this parameter in the above doc of the method

2021-09-09 23:40 UTC, Kadino requested changes
Whether parallel-misbehaving GoogleTest modules should be blocked until fixed is an interesting question.
+carlitosan who recently ran into such an issue

Providing the ability to move a module to execute non-parallel could drain away the parallelization of tests, and hurt execution times. Not providing this feature (or only providing it through CMake attribute hack-arounds) does more forcefully prompt fixing a parallel-only issue, instead of deferring it via enabling serial. This would technically be new acceptance criteria for writing GTest tests, which we can make explicit.

I am in favor of explicitly not providing this option, and adding documentation why. My primary reasoning is that cleanly executing in parallel can be significantly difficult to achieve after you lose it. Down the line, we can field individual discussions on cases where GTest tests really want to execute serial.

2021-09-10 00:01 UTC, evanchia-ly-sdets commented
Based on conversations we have decided to not implement this feature.

2021-09-10 00:01 UTC, closed without merging