Fix the crash when switching between sim obj and physix layout in animation editor.
o3de/o3de pull request #4185
Opened 2021-09-17 05:07 UTC by amzn-rhhong

Resolves #4165

2021-09-17 05:09 UTC, amzn-rhhong commented
The problem is that m_selectedModelIndices became stall when switching actors (also when deleting it).
The selection model should store the correct selection indices already, so we should just queue that every time we call reinit.

2021-09-17 06:42 UTC, amzn-jillich approved these changes

2021-09-17 17:52 UTC, AMZN-Gene approved these changes

2021-09-21 10:02 UTC, amzn-jillich requested changes

2021-09-21 10:02 UTC, amzn-jillich commented on Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
> +        const QModelIndexList& selectedModelIndices = GetSelectedModelIndices();
This is not safe. GetSelectedModelIndices() is returning a copy now. The returned copy might get destructed after this line and the reference might be invalid. Can you remove the ref here?

2021-09-22 16:39 UTC, amzn-jillich approved these changes

2021-09-22 16:41 UTC, amzn-jillich commented on Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
> +        const QModelIndexList& selectedModelIndices = GetSelectedModelIndices();
Ah ok, good to know. I wasn't sure that all compilers are safe using that. Just shipped, still would prefer to just hold a copy in this case as the copy will be hold by the compiler internally anyway to make it safe while it seems kind of hidden when looking at the code that it is returning a copy.

2021-09-22 16:41 UTC, merged