License Info is Displayed a Clickable Link in Gem Catalog + Other Inspector Improvements
o3de/o3de pull request #5272
Opened 2021-11-03 20:07 UTC by AMZN-nggieber

Also some general improvements to gem inspector including: Adding text eliding, fixing typos and conditional spacing.
Add adds license and license_url as modifiable properties in in o3de scripts.

![HQX9QQIwT1](https://user-images.githubusercontent.com/52797929/140184563-92b72705-1411-443c-a3d8-2ac9452a02b4.gif)
![eja0Yt75d0](https://user-images.githubusercontent.com/52797929/140184551-60ae323a-8aa4-4f88-8702-a335f71f4c84.gif)

F:\o3de\o3de\python>python.cmd -m pytest F:\o3de\o3de\scripts\o3de\tests\unit_test_gem_properties.py --build-directory F:\o3de\o3de\build\windows_vs2019\bin\profile
================================================= test session starts =================================================
platform win32 -- Python 3.7.10, pytest-5.3.2, py-1.9.0, pluggy-0.13.1
rootdir: F:\o3de\o3de, inifile: pytest.ini
plugins: mock-2.0.0, timeout-1.3.4, ly-test-tools-1.0.0
collected 3 items

..\scripts\o3de\tests\unit_test_gem_properties.py ...                                                            [100%]

================================================== 3 passed in 0.05s ==================================================

2021-11-03 20:42 UTC, AMZN-alexpete commented
This is great, but I think the license URL for all of our gems should point to LICENSE.txt in our GitHub repo https://github.com/o3de/o3de/blob/development/LICENSE.txt which covers MIT, Apache and other specifics about the licenses, and will also be kept up to date incase the license changes.

2021-11-03 20:43 UTC, AMZN-alexpete commented on Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
> +            m_dependingGems->hide();
excellent!

2021-11-04 01:04 UTC, AMZN-ScottR approved these changes
Could use a `tr()` pass on display strings but looks fine otherwise.

2021-11-04 17:12 UTC, AMZN-alexpete requested changes
Looks good, just one change which is to not use the O3DE license as the default license_url for the templates.

2021-11-04 17:12 UTC, AMZN-alexpete commented on Templates/AssetGem/Template/gem.json
> +    "license_url": "https://github.com/o3de/o3de/blob/development/LICENSE.txt",
let's not make the default license URL point to our repo

2021-11-04 17:12 UTC, AMZN-alexpete commented on Templates/CppToolGem/Template/gem.json
> +    "license_url": "https://github.com/o3de/o3de/blob/development/LICENSE.txt",
ditto here, this should be blank

2021-11-04 17:12 UTC, AMZN-alexpete commented on Templates/DefaultGem/Template/gem.json
> +    "license_url": "https://github.com/o3de/o3de/blob/development/LICENSE.txt",
ditto here, this should be blank

2021-11-04 17:12 UTC, AMZN-alexpete commented on Templates/PythonToolGem/Template/gem.json
> +    "license_url": "https://github.com/o3de/o3de/blob/development/LICENSE.txt",
ditto here, this should be blank

2021-11-04 17:50 UTC, AMZN-alexpete approved these changes

2021-11-04 17:52 UTC, AMZN-Phil approved these changes

2021-11-04 20:04 UTC, merged