The Build Time Stamp of ShaderAsset And
o3de/o3de pull request #5373
Opened 2021-11-05 16:19 UTC by galibzon

ShaderVariantAsset Should Be Based On
GetTimeUTCMilliSecond()

GetTimeNowMicroseconds() is useful to measure time stamp differences.
GetTimeUTCMilliSecond() is for time stamps based on absolute clock/wall time.

Signed-off-by: galibzon <66021303+galibzon@users.noreply.github.com>

2021-11-05 17:21 UTC, rgba16f approved these changes

2021-11-05 18:46 UTC, santorac requested changes

2021-11-05 20:50 UTC, galibzon commented on Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
> +                AZStd::GetTimeUTCMilliSecond() - shaderAssetBuildTimestamp);
fixed.

2021-11-12 19:50 UTC, santorac approved these changes

2021-11-12 19:51 UTC, merged