[LYN-8041] Enable relocation of the Project Game Release Layout
o3de/o3de pull request #5380
Opened 2021-11-05 19:57 UTC by lumberyard-employee-dm

Relocating the Project Game Release Layout to another directory on the file system failed due to the querying of the engine root failing due to the ComponentApplication::m_engineRoot not using the project path stored in the SettingsRegisry if the engine root cannot be detected

Removed the ApplicationRequestBus GetEngineRoot function.
The ComponentApplicationRequestBus has a function of the same name that returns the same path.

Removed the deprecated GetAppRoot function.
The path it returns has no defined value. It was not the engine root or the project root.
Removed unused CFileUtil and CFileUtil_impl functions that were invoking the ApplicationREquestBus GetEngineRoot function.
On the way to update the functions it was discovered that they aren't called, so they were removed

Added a CalculateBranchToken overload that can populate a fixed_string to avoid heap allocations

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

2021-11-05 21:18 UTC, amzn-phist requested changes

2021-11-05 21:18 UTC, amzn-phist commented on Gems/Atom/Feature/Common/Code/Source/LuxCore/LuxCoreRenderer.cpp
> +            AZ::IO::FixedMaxPath luxCoreExeFullPath = AZ::Utils::GetEnginePathy();
`GetEnginePathy` -> `GetEnginePath`

2021-11-05 23:12 UTC, lumberyard-employee-dm commented on Gems/Atom/Feature/Common/Code/Source/LuxCore/LuxCoreRenderer.cpp
> +            AZ::IO::FixedMaxPath luxCoreExeFullPath = AZ::Utils::GetEnginePathy();
Good thing this code is #ifdef out.

2021-11-08 16:26 UTC, amzn-phist approved these changes

2021-11-09 01:03 UTC, AMZN-koppersr approved these changes

2021-11-09 01:40 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/StringFunc/StringFunc.cpp
> +                            ? '_' : static_cast<char>(std::tolower(element));
We don't have an `AZStd::tolower` for individual charrs

2021-11-09 18:03 UTC, merged