DiffuseProbeGridDownsample disable
o3de/o3de pull request #5518
Opened 2021-11-10 21:26 UTC by tjmgd

The DiffuseProbeGridDownsample pass process currently runs even when there is no Diffuse Probe Grid in a level. This can be a significant overhead for some devices. This fix prevents the problem by adding a corresponding class for the pass, and implementing an IsEnabled check.

2021-11-15 19:47 UTC, Adi-Amazon requested changes
Since the sole purpose of this class is to implement the Enable/Disable to remove the computation, this needs to be mentioned in the header so that in the future it might be changed / removed if there are other options (for example - removing the pass from a parent class pass via code might also be a viable option)

2021-11-15 20:21 UTC, Adi-Amazon commented on Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridDownsamplePass.cpp
> +//#include <RayTracing/RayTracingFeatureProcessor.h>
nit: remove

2021-11-15 20:21 UTC, Adi-Amazon commented on Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
> +	Source/DiffuseGlobalIllumination/DiffuseProbeGridDownsamplePass.cpp
nit: indent

2021-11-15 20:21 UTC, Adi-Amazon approved these changes

2021-11-19 16:20 UTC, rgba16f commented
Previous build failed. Started a new one today after the updates.
https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-5518/

2021-11-19 19:25 UTC, rgba16f commented
@tjmgd It looks like you have some tab characters in the file

VALIDATION FAILURE SUMMARY
VALIDATOR_FAILED: TabsValidator D:\workspace\o3de\Gems\Atom\Feature\Common\Code\atom_feature_common_files.cmake::TabsValidator FAILED TabsValidator - 1 tabs in this file
    First instance of a tab: 
         +    Source/DiffuseGlobalIllumination/DiffuseProbeGridRenderPass.h
    ---> +\tSource/DiffuseGlobalIllumination/DiffuseProbeGridDownsamplePass.cpp

2021-12-06 13:56 UTC, hultonha commented
Kicked off another build - https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-5518/

2021-12-10 16:39 UTC, lawsonamzn commented
what happened here? was this dropped?  Looks like the build succeeded but it was 4 days ago, so another might need to be done?

2021-12-10 16:58 UTC, hultonha commented
> what happened here? was this dropped? Looks like the build succeeded but it was 4 days ago, so another might need to be done?

This should be okay to merge, might want to update to be safe, sorry I missed hitting the merge button soon (maybe @rgba16f or @Adi-Amazon can do the honors as-is?) Seems unlikely this will cause a failure but it's a small risk

2021-12-10 18:28 UTC, moudgils commented
> > what happened here? was this dropped? Looks like the build succeeded but it was 4 days ago, so another might need to be done?
> 
> This should be okay to merge, might want to update to be safe, sorry I missed hitting the merge button soon (maybe @rgba16f or @Adi-Amazon can do the honors as-is?) Seems unlikely this will cause a failure but it's a small risk

There was an issue with this PR. @dmcdiarmid-ly should make the final call if the PR is look too merge.

2021-12-14 09:40 UTC, tjmgd commented
> > > what happened here? was this dropped? Looks like the build succeeded but it was 4 days ago, so another might need to be done?
> > 
> > 
> > This should be okay to merge, might want to update to be safe, sorry I missed hitting the merge button soon (maybe @rgba16f or @Adi-Amazon can do the honors as-is?) Seems unlikely this will cause a failure but it's a small risk
> 
> There was an issue with this PR. @dmcdiarmid-ly should make the final call if the PR is ok to merge.

What was the issue in question? This PR has a sister PR that is very similar so it is important to know for future reference. Can I expect a decision in the near future on this?

2021-12-14 19:46 UTC, moudgils commented
> > > > what happened here? was this dropped? Looks like the build succeeded but it was 4 days ago, so another might need to be done?
> > > 
> > > 
> > > This should be okay to merge, might want to update to be safe, sorry I missed hitting the merge button soon (maybe @rgba16f or @Adi-Amazon can do the honors as-is?) Seems unlikely this will cause a failure but it's a small risk
> > 
> > 
> > There was an issue with this PR. @dmcdiarmid-ly should make the final call if the PR is ok to merge.
> 
> What was the issue in question? This PR has a sister PR that is very similar so it is important to know for future reference. Can I expect a decision in the near future on this?

I have pinged @dmcdiarmid-ly about this PR.

2021-12-14 19:54 UTC, wintermute-motherbrain commented
We have a PR incoming that will address this.  Please hold off on merging this as the new PR handles edge cases not covered by this PR

2021-12-14 19:55 UTC, closed without merging

2021-12-15 12:05 UTC, tjmgd commented
Can I get a link for the new PR? When is it expected to be approved?

2021-12-15 17:36 UTC, wintermute-motherbrain commented
Hi TJ, yes apologies I thought the PR was already ready (hopefully will be soon) and seems I was premature in closing this ticket.  Once the PR is up @dmcdiarmid-ly can link it here.  The main concern was around potential undefined behavior.