Expand the Display Mapper component p0 test so that it modifies at least 1 property before passing.
o3de/o3de pull request #5914
Opened 2021-11-24 19:07 UTC by jromnoa

- Entered as a result of this issue discovered by an end user: https://github.com/o3de/o3de/issues/5864 
- A test for the Diffuse Global Illumination component will be added in the near future as well (work scoped).

2021-11-24 23:10 UTC, amzn-tommy approved these changes
Looks good, and an improvement to the existing test. Just keep in mind that the crash bug that prompted this change only occurs when the DisplayMapper component is added to the level entity, not a regular entity as is done in this test.

We should follow up to determine if it should be allowed only on regular entities, only on the level entity, or both, and adjust the test to cover the valid uses.

2021-11-29 18:21 UTC, mrieggeramzn approved these changes

2021-11-29 20:04 UTC, smurly requested changes
a docstring should specify that 'LDR color Grading LUT' is an Asset.id so that future users will know how to use the property in automation.

2021-11-29 20:04 UTC, smurly commented on AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
>          """
need a docstring for the new property

2021-11-30 23:27 UTC, smurly approved these changes

2021-12-01 19:12 UTC, merged