Add additional check to ensure material library is loaded when trying to retrieve names.
o3de/o3de pull request #6050
Opened 2021-11-30 21:05 UTC by AMZN-daimini

Adds ulterior check to ensure the PhysX material library asset is loaded correctly before trying to get materials data.

https://github.com/o3de/o3de/issues/6027

Signed-off-by: Danilo Aimini <82231674+AMZN-daimini@users.noreply.github.com>

2021-11-30 21:18 UTC, cgalvan approved these changes

2021-11-30 22:18 UTC, lumberyard-employee-dm approved these changes

2021-12-02 15:04 UTC, moraaar commented
I've investigated issue #6027 to find out why physics material library is not ready and I just discovered something odd.

If I run the editor after Asset Processor has finished, the function `PhysXSystem::OnCatalogLoaded` is called correctly, which is the one that loads the physics material library if there is one assigned or triggers the logic to create the default one if there is none assigned to the PhysXS configuration.

But if I run the editor while there is no cache folder yet, the asset processor will open, start processing, editor will hold until SOME (not all) assets are processed, then open the editor, but the function `PhysXSystem::OnCatalogLoaded` will NEVER be called, even after Asset Processor fully finished.

Since `PhysXSystem::OnCatalogLoaded` never gets called in that scenario (which is the one from #6027), then for a new project the default physics material library will never be created and it crashes the first time some code asks for it (fbx setting in the case of #6027). For an existing project (for example `AutomatedTesting`) the physics material library assigned will not be loaded and it will just return "Default Material", which would be incorrect.

So to properly fix #6027 we have to:
1. Mark `.physmaterial` assets as criticals so the editor doesn't open without Asset Processor processing them. I'll put another comment in this PR on how to do it.
2. Find out why `OnCatalogLoaded` is not being broadcast when the editor is launched before processing any asset. I'll file another Github bug for this.

2021-12-02 15:08 UTC, moraaar requested changes

2021-12-02 18:41 UTC, AMZN-daimini commented on Gems/PhysX/Code/Source/Pipeline/MeshGroup.cpp
> +                    physicsConfiguration && physicsConfiguration->m_materialLibraryAsset)
Yeah I figured this was just an extra check against crashes, but does not really fix the underlying problem.

I will add the change you requested asap :)

2021-12-03 00:48 UTC, AMZN-daimini commented on Gems/PhysX/Code/Source/Pipeline/MeshGroup.cpp
> +                    physicsConfiguration && physicsConfiguration->m_materialLibraryAsset)
Marked physmaterial assets as critical as requested :)

2021-12-03 09:44 UTC, moraaar approved these changes

2021-12-03 11:25 UTC, merged