Enable optimized GPU tests and make them the main GPU tests.
o3de/o3de pull request #6085
Opened 2021-12-02 02:52 UTC by jromnoa

- Deletes the old scripts.
- Adds the new optimized versions.
- Only the benchmarks and test that opens MaterialEditor use old hydra utils, but we can transition those later (they don't use any log lines or undesired test verification methods).
- Still working out a clean run, but wanted to get the PR started early.

2021-12-02 22:33 UTC, jromnoa commented
Will be able to have this reviewed once I push out my next to update to clean the test up

2021-12-03 19:11 UTC, NeilGitGud approved these changes

2021-12-06 19:56 UTC, smurly requested changes
atom_constants.py docstrings

2021-12-06 19:56 UTC, smurly commented on AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
> +            'Outer angle': 'Controller|Configuration|Shutters|Outer angle',
docstring needed for property path constants

2021-12-07 01:01 UTC, smurly approved these changes

2021-12-07 18:52 UTC, merged