Fix: function name incorrect in Lua editor
o3de/o3de pull request #6216
Opened 2021-12-07 15:32 UTC by tjmgd

Signed-off-by: T.J. McGrath-Daly <tj.mcgrath.daly@huawei.com>

2021-12-10 18:32 UTC, lumberyard-employee-dm requested changes
Since the LuaScript gem is a new gem being added to the Engine, could you write up an [RFC](https://github.com/o3de/sig-core/issues/new/choose) which details the purpose and functionality of the new Gem?

2021-12-10 18:32 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/Script/ScriptAdapterBus.h
> + */
This would need to use the O3DE copyright in order to contribute to O3DE

2021-12-10 18:32 UTC, lumberyard-employee-dm commented on engine.json
> +        "UCDDemo",
I don't believe you intended to add this project to the engine

2021-12-10 18:32 UTC, lumberyard-employee-dm commented on Gems/LuaScript/gem.json
> +}
This gem.json is using an older gem.json format which is not compatible with O3DE

Creation of new gems should be done via the `scripts\o3de.bat create-gem` command which will use the newer project templates.

2021-12-10 20:28 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/Script/ScriptAdapterComponent.cpp
> +    const int ScriptAdapterComponent::NAME_BUFFER_SIZE = 64;
This implementation is Windows specific and would need to be Platform abstracted to allow for implementations on for the other supported platforms.

Pathwise using backslashes should be avoided and a dedicated path class like [AZ:IO::Path/AZ::IO::FixedMaxPath/AZ::IO::PathView](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/IO/Path/Path.h) should be used.

Also constant variables names would need to be updated to fit within the coding standard of [UpperCamelCase](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#constant-names)

2021-12-10 20:32 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/Script/ScriptAdapterComponent.cpp
> +    }
I am assuming this logic was implemented in Lumberyard 1.X.

The AZ::Utils namespace has a [GetProjectPath](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Utils/Utils.h#L77-L78) function in it that doesn't assume the project is located with the engine root, nor does the code assume that the directory of the project is the same as the project name.

2021-12-10 20:40 UTC, lumberyard-employee-dm commented
Also could provide a more detail description on what this is fixing in the Lua Editor and perhaps a screenshot of where the issue is occurring in the Lua Editor

2021-12-10 22:08 UTC, lawsonamzn commented
This change seems to actually be 2 different changes.  One appears to be a fix for something going on with the LUA Script Asset field.   But the description does not explain what bug this fixes or what is wrong, and I can't find an issue that its related to.

The other change appears to be a completely new feature - the ability for the asset browser's preview window to display the text of a script as a preview.  This is good, although, it should probably be added as a separate PR that addresses just that feature.  In addition, I'd recommend putting it in AzToolsFramework for now, since thats where the rest of the Lua Script Editor functionality lives.   In the future we can create a gem for all of the LUA functionality and split it out and move it there.  But until then, this is probably too small a feature to warrant the creation of a gem.

2022-01-28 09:51 UTC, hultonha commented
Any update on this @tjmgd after the PR feedback? Are you okay splitting this PR to have one be the fix and the other be the new feature? Were you able to respond to the feedback from @lumberyard-employee-dm too? Thanks!

2022-01-28 11:54 UTC, tjmgd commented
> Any update on this @tjmgd after the PR feedback? Are you okay splitting this PR to have one be the fix and the other be the new feature? Were you able to respond to the feedback from @lumberyard-employee-dm too? Thanks!

I am waiting to hear back from somebody on my end here about this. Apologies for the delay!

> Any update on this @tjmgd after the PR feedback? Are you okay splitting this PR to have one be the fix and the other be the new feature? Were you able to respond to the feedback from @lumberyard-employee-dm too? Thanks!

I am waiting for some feedback on my end. Would you prefer if I converted to draft in the meantime?

2022-01-28 12:51 UTC, hultonha commented
> > Any update on this @tjmgd after the PR feedback? Are you okay splitting this PR to have one be the fix and the other be the new feature? Were you able to respond to the feedback from @lumberyard-employee-dm too? Thanks!
> 
> I am waiting to hear back from somebody on my end here about this. Apologies for the delay!
> 
> > Any update on this @tjmgd after the PR feedback? Are you okay splitting this PR to have one be the fix and the other be the new feature? Were you able to respond to the feedback from @lumberyard-employee-dm too? Thanks!
> 
> I am waiting for some feedback on my end. Would you prefer if I converted to draft in the meantime?

No worries about the delay @tjmgd, I just wanted to make sure this didn't get forgotten about 🙂 If it's not quite ready for a full review yet then switching to draft would be great, thank you! You can tag me and the other reviewers when it's ready for review again. Thanks!

2025-04-01 22:32 UTC, closed without merging