Check whether env variables are defined
o3de/o3de pull request #6229
Opened 2021-12-07 22:11 UTC by AMZN-Phil

Check whether environment variables are defined instead of checking the env variable contents. Avoids the conditional failing with version numbers of 3 digits, such as 21.11.1.

Signed-off-by: AMZN-Phil <pconroy@amazon.com>

2021-12-07 22:16 UTC, Pi-Bouf approved these changes

2021-12-07 22:21 UTC, amzn-changml approved these changes

2021-12-07 22:22 UTC, lumberyard-employee-dm approved these changes
So `if("21.11.1")` would be true within CMake.

2021-12-07 22:23 UTC, amznestebanpapp approved these changes

2021-12-07 22:26 UTC, amznestebanpapp commented
> So `if("21.11.1")` would be true within CMake.

yeah, not sure what the error is here. The only issue I see is that someone could define the environment variable to empty, in which case IMO it should not be set. That was the reason why it was written that way, if there is e.g. a Jenkins parameter that is not set, it will still be defined (with an empty value). So this was written to prevent that problem.

"21.11.1" should have not given an error in that condition. In CMake, an variable expands to empty string if not defined. The if would then become `if("")` which evaluates to `FALSE` (in CMake, empty strings evaluates to `FALSE`)

2021-12-07 22:27 UTC, amznestebanpapp requested changes
leaving it as requested changes to get more clarification before it gets merged in

2021-12-07 22:37 UTC, amzn-changml commented
> > So `if("21.11.1")` would be true within CMake.
> 
> yeah, not sure what the error is here. This was written that way to prevent a Jenkins parameter from setting the value. In Jenkins, when a parameter is defined, it defines an environment variable, and its always defined. So we need to check for the value of it to know if the user did something with it or not.
> 
> "21.11.1" should have not given an error in this condition. In CMake, a variable expands to empty string if not defined. The if would become `if("")` which evaluates to `FALSE` (in CMake, empty strings evaluates to `FALSE`)

The observed behavior is `21.11` evaluates true (and sets version accordingly) but `21.11.1` evaluates false. Agreed that while this change is valid, it may not solve the root issue. I know that CMake has some built-in version number conditionals but not sure if this variable is being evaluated as a string if detected as a semver

2021-12-07 22:44 UTC, AMZN-Phil commented
If the intent is also to be able to have this defined as an empty string and have that skip the LY_VERSION_STRING set I can replace the version check with if("$ENV{O3DE_VERSION}" VERSION_GREATER "0.0.0.0") and the build version as if("$ENV{O3DE_BUILD_VERSION}" GREATER "0")? 

I want to run this through a few more checks before updating the PR but that looks like it works for the standard cases.

2021-12-07 22:44 UTC, amznestebanpapp commented
> The observed behavior is `21.11` evaluates `TRUE` (and sets version accordingly) but `21.11.1` evaluates `FALSE`. Agreed that while this change is valid, unsure if it will solve the root issue. I know that CMake has some built-in version number conditionals but not sure if this variable is being evaluated as a string (and returns a boolean) if detected as a semver pattern

Gotcha, what is going on is that CMake is evaluating it as a number instead of a string. This should cover both cases:
```
if(NOT "$ENV{O3DE_VERSION}" STREQUAL "") # Forcing evaluation as a string
```

2021-12-07 22:47 UTC, lumberyard-employee-dm commented
> > The observed behavior is `21.11` evaluates `TRUE` (and sets version accordingly) but `21.11.1` evaluates `FALSE`. Agreed that while this change is valid, unsure if it will solve the root issue. I know that CMake has some built-in version number conditionals but not sure if this variable is being evaluated as a string (and returns a boolean) if detected as a semver pattern
> 
> Gotcha, what is going on is that CMake is evaluating it as a number instead of a string. This should cover both cases:
> 
> ```
> if(NOT "$ENV{O3DE_VERSION}" STREQUAL "") # Forcing evaluation as a string
> ```

Wouldn't `0.0.0.0` still evaluate as string though due to the multiple `.` characters?

2021-12-07 22:50 UTC, amznestebanpapp commented
> 



> 0.0.0.0

Yes, I would expect it to always evaluate as a string in this case. I think is a CMake bug, it must start considering as a number and then fail to parse the number and end up with a false evaluation (since different than 0). But if it fails to parse it as a number, it should assume is a string

2021-12-08 00:05 UTC, lumberyard-employee-dm submitted a review, later dismissed

2021-12-08 00:08 UTC, amznestebanpapp reviewed
this wont work either... eventually the "O3DE_VERSION" for the development branch will be "development" and the one for stabilization will be "stabilization" and the one for source code will be "source"

2021-12-08 00:35 UTC, AMZN-Phil commented
I can force the evaluation as a string as suggested for now, which will fix the issue allow for build numbers to be part of the version string. However passing a text value through as the version currently without any additional change won't work since LY_VERSION_STRING is used to set CPACK_PACKAGE_VERSION. I'm not sure on the allowed formats of that variable but even if that allows a string as a version, the Windows installer would need extra changes. Currently WiX is using CPACK_PACKAGE_VERSION as its version number as a 8bit.8bit.16bit.x version number.

2021-12-08 00:49 UTC, amznestebanpapp commented
> I can force the evaluation as a string as suggested for now, which will fix the issue allow for build numbers to be part of the version string. However passing a text value through as the version currently without any additional change won't work since LY_VERSION_STRING is used to set CPACK_PACKAGE_VERSION. I'm not sure on the allowed formats of that variable but even if that allows a string as a version, the Windows installer would need extra changes. Currently WiX is using CPACK_PACKAGE_VERSION as its version number as a 8bit.8bit.16bit.x version number.

yes, we will need extra changes. The version is also assumed as a certain format to present in the Editor
I wouldnt go with numbering for those branches because is unknown what those branches will be. We current generate installers for them and they create confusion, its hard to tell what someone installed if they installed from development/stabilization nightly installers. My hope is that we just record the branch name and commit id somehow. For the version passed to WIX, we may need to default back to 0.0.0.0 for these cases but we may be able to just show it in the UI. 
For deb packages, you can pass something like "dev" as part of the version, but we will need to experiment with it.

2021-12-08 01:38 UTC, amznestebanpapp approved these changes

2021-12-08 20:34 UTC, merged