Fix: Lua editor can open the same file repeatedly
o3de/o3de pull request #6330
Opened 2021-12-10 11:49 UTC by tjmgd

Lua editor can open the same file repeatedly through different opening methods

Signed-off-by: T.J. McGrath-Daly <tj.mcgrath.daly@huawei.com>

2021-12-10 18:05 UTC, lumberyard-employee-dm commented on Code/Tools/Standalone/Source/LUA/LUAEditorMainWindow.cpp
> +                if (entry_type == AzToolsFramework::AssetBrowser::AssetBrowserEntry::AssetEntryType::Source)
standards: The variable naming standard should be [lowerCamelCase](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#variable-names)

2021-12-13 16:01 UTC, lsemp3d requested changes
Correct the variable name convention per lumberyard-employee-dm's review

2021-12-27 19:21 UTC, cgalvan requested changes

2021-12-27 19:21 UTC, cgalvan commented on Code/Tools/Standalone/Source/LUA/LUAEditorMainWindow.cpp
> +                    EBUS_EVENT(Context_DocumentManagement::Bus, OnLoadDocument, filePath, true);
While we're moving this code, we should also update to not use the old macro style ebus call. The updated one would look like:

```
Context_DocumentManagement::Bus::Broadcast(&Context_DocumentManagement::OnLoadDocument, filePath, true);
```

2022-01-28 09:55 UTC, hultonha commented
Any update on this @tjmgd? Looks like some feedback was requested but there hasn't been an update. If you ping me when the updates have been made I can kick off a build. Thanks!

2022-01-28 12:56 UTC, tjmgd commented
> Any update on this @tjmgd? Looks like some feedback was requested but there hasn't been an update. If you ping me when the updates have been made I can kick off a build. Thanks!

I am closing this PR and opening a new one once the changes are made. Ran into git problems!

2022-01-28 12:56 UTC, closed without merging

2022-01-28 12:57 UTC, hultonha commented
> > Any update on this @tjmgd? Looks like some feedback was requested but there hasn't been an update. If you ping me when the updates have been made I can kick off a build. Thanks!
> 
> I am closing this PR and opening a new one once the changes are made. Ran into git problems!

No problem, thanks for the update @tjmgd, I'd go ahead and add the original reviewers and myself when it's posted. Thanks!