Fixing character controller triggering collision on creation
o3de/o3de pull request #6546
Opened 2021-12-22 19:59 UTC by AMZN-mnaumov

Looks like character controller does not initialize starting position

https://github.com/o3de/o3de/issues/2762

Signed-off-by: Mikhail Naumov <mnaumov@amazon.com>

2021-12-22 20:51 UTC, NicholasVanSickle approved these changes

2021-12-23 02:03 UTC, amzn-rhhong approved these changes

2021-12-29 13:16 UTC, SergeyAMZN requested changes

2021-12-29 13:16 UTC, SergeyAMZN commented on Gems/PhysX/Code/Source/PhysXCharacters/API/CharacterUtils.cpp
> +            controllerDesc.position = PxMathConvertExtended(extendedConfig.m_position);
Could you move this line to the `AppendShapeIndependentProperties` function above since position isn't PhysX specific?

2022-01-03 21:17 UTC, AMZN-koppersr approved these changes

2022-01-04 14:53 UTC, moraaar approved these changes

2022-01-07 00:40 UTC, SergeyAMZN approved these changes

2022-01-07 01:09 UTC, merged