Ragdoll Crash
o3de/o3de pull request #6667
Opened 2022-01-04 15:33 UTC by tjmgd

When the rag doll effect is created for the NZ_01 model and Ragoll is added to the NZ_01 skeleton of the NZ_01 model, the game will crash when it exits the running state.

2022-01-27 20:02 UTC, spham-amzn commented on Code/Tools/SceneAPI/SceneBuilder/SceneImporter.cpp
> +                            nodeName = tmpName + AZStd::string::format("%d", num++);
you could also do
```suggestion
                            nodeName = AZStd::string::format("%s%d", tmpName.c_str(), num++); 
```

2022-02-08 15:34 UTC, greerdv commented
@alexmontAmazon @AMZN-stankowi this looks like something you might have input on?

2022-02-08 15:54 UTC, AMZN-stankowi approved these changes

2022-02-15 11:41 UTC, amzn-jillich requested changes

2022-02-15 11:41 UTC, amzn-jillich commented on Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
> +                jointLimitConfig->SetPropertyVisibility(AzPhysics::JointConfiguration::PropertyVisibility::ChildLocalRotation, jointLimitConfig != nullptr);
Rather than returning entirely here, can you just hide the `m_jointLimitWidget`?

2026-07-05 12:21 UTC, closed without merging