Empty Anim Graph
o3de/o3de pull request #6669
Opened 2022-01-04 15:39 UTC by tjmgd

After a workspace is created in the Animation Editor, the Anim Graph is not completely reset. The Anim Graph of the previous workspace is still retained, but the content is empty.

2022-01-04 17:19 UTC, cgalvan approved these changes

2022-01-13 18:17 UTC, amzn-rhhong commented on Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphModel.cpp
> +            emit RemoveAll();
I don't think we need a custom emit signal like this. During the remove of modelItemData it is already emit remove signal.

2022-01-13 18:18 UTC, amzn-rhhong commented on Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NavigationLinkWidget.cpp
> +        connect(&m_plugin->GetAnimGraphModel(), &AnimGraphModel::RemoveAll, this, &NavigationLinkWidget::ClearModelIndex);
I think you could subscribed to the beginRemoveRows signal and clear out the m_modelIndexes one by one, then update the breadCrumbs.

2022-01-13 18:19 UTC, amzn-rhhong requested changes
please see feedback

2026-07-05 12:22 UTC, closed without merging