Fixed script canvas component asset not being found
o3de/o3de pull request #6727
Opened 2022-01-06 17:14 UTC by moraaar

Script canvas component has the member `m_sourceData` (that points to the script canvas asset) that internally has data, id and path. Path is serialized as the absolute path of the pc that is saving the level.

So when another pc loads the same level it cannot find the script canvas asset.

The function `CompleteDescription` takes a look at the id and takes the path from the asset catalog, but at the moment it's doing an early return because id and path are not empty (but path is the value serialized from other user saving the level).

By changing the early return condition from "check if id and path are not empty" to "check if data is already valid" then it it will resolve by using id, looking into the catalog and getting the real path.

This fix makes several physics automated tests that relied on script canvas to work.

Signed-off-by: moraaar <moraaar@amazon.com>

2022-01-06 17:19 UTC, lsemp3d approved these changes

2022-01-06 17:58 UTC, carlitosan requested changes
Don't check IsGraphValid in this function. just don't early return on a complete path. Check for and ID, and if it is there, get a path based on that id. If there is a path, get an ID from that path, and do the above steps again, to make sure there is no absolute path saved out in the description.

2022-01-06 18:09 UTC, moraaar commented
> Don't check IsGraphValid in this function. just don't early return on a complete path. Check for and ID, and if it is there, get a path based on that id. If there is a path, get an ID from that path, and do the above steps again, to make sure there is no absolute path saved out in the description.

Done, removed early return, the function already works as you describe it.

2022-01-07 18:05 UTC, carlitosan approved these changes

2022-01-07 22:57 UTC, cgalvan approved these changes

2022-01-10 09:05 UTC, merged