fix launcher not showing gems
o3de/o3de pull request #7015
Opened 2022-01-19 22:01 UTC by byrcolin

Signed-off-by: byrcolin <byrcolin@amazon.com>

2022-01-19 22:24 UTC, lumberyard-employee-dm approved these changes

2022-01-19 22:36 UTC, amzn-phist approved these changes

2022-01-19 23:22 UTC, AMZN-alexpete requested changes
It appears that two methods are still missing from manifest.py
```
get_repo_json_data
get_repo_path
```
Looking into whether this is a bug in ProjectManager or was changed.

2022-01-20 01:09 UTC, merged

2022-01-20 17:59 UTC, AMZN-nggieber reviewed
Looks like this will fix some of the issues, awesome!