Add `AZStd::ranges::all_of` and `AZStd::ranges::any_of`
o3de/o3de pull request #7650
Opened 2022-02-15 20:22 UTC by burelc-amzn

Signed-off-by: Chris Burel <burelc@amazon.com>

2022-02-15 20:25 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
> +                return ranges::find_if_not(first, last, std::ref(pred), std::ref(proj)) == last;
If you include `AzCore/std/reference_wrapper.h` file, the `AZStd::ref` name can be used instead(`AZStd::ref` is just std::ref, but with just bring that name into the AZStd namespace)

2022-02-15 20:27 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
> +            template<class I, class S, class Proj = identity, class Pred,
You need to swap the `Pred` and `Proj` parameters around, as Pred doesn't have a default value, while Proj does.
This will not compile on clang.

2022-02-15 20:31 UTC, lumberyard-employee-dm requested changes
You should add UnitTest for these functions to [RangesAlgorithmTests.cpp](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp)

2022-02-23 21:10 UTC, lumberyard-employee-dm approved these changes

2022-02-24 21:13 UTC, mbalfour-amzn approved these changes
LGTM!

2022-03-02 17:22 UTC, lumberyard-employee-dm commented
@burelc-amzn Are you ready to merge this PR?

2022-03-04 01:01 UTC, merged