Focus Mode Visual Feedback: Pass Classes
o3de/o3de pull request #7678
Opened 2022-02-16 15:39 UTC by jonawals

This PR contains the pass class files for the Editor Mode Visual Feedback system necessary to implement the Focus Mode visual feedback effects (the rest of the work will come in subsequent PRs).

2022-02-17 18:11 UTC, antonmic requested changes
Looks good, but some overrides should be removed, otherwise proper pass functionality will be impaired surrounding enabled flags set in JSON

2022-02-17 18:11 UTC, antonmic commented on Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeOutlinePass.cpp
> +        }
Same, remove this override

2022-02-17 18:11 UTC, antonmic commented on Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeTintPass.cpp
> +        }
Same, remove

2022-02-28 16:27 UTC, jonawals commented on Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeBlurPass.cpp
> +        }
Fixed 👍

2022-02-28 16:34 UTC, jonawals commented on Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeFeedbackParentPass.cpp
> +        }
Fixed 👍

2022-02-28 16:37 UTC, jonawals commented on Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeFeedbackPassBase.cpp
> +            RPI::Ptr<EditorModeFeedbackPassBase> pass = aznew EditorModeFeedbackPassBase(descriptor);
I'm inheriting the parent `FullscreenTrianglePass` class constructors like so: 

```
using AZ::RPI::FullscreenTrianglePass::FullscreenTrianglePass;
```

2022-02-28 16:38 UTC, jonawals commented on Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeOutlinePass.cpp
> +        }
Fixed 👍

2022-02-28 17:06 UTC, closed without merging