Fix NoneType errors in EditorTest
o3de/o3de pull request #7736
Opened 2022-02-18 00:26 UTC by Kadino

Reduces EditorTest NoneType errors, remove dead code, update docstrings, fix pep8 warnings.

Addresses a failure seen in https://github.com/o3de/o3de/issues/7657 which unexpectedly removed test reporting from an AR failure.

Signed-off-by: sweeneys <sweeneys@amazon.com>

2022-02-18 01:17 UTC, Kadino commented
Fixed some initialized-as-mutable attributes, but avoided addressing all data lifetime concerns. There are a number of class-stored attributes that may cause problems to existing scripts if they are move to instance-level ones. Most of these concerns will require a larger change, such as changes to `cmdline_args` also needing to modify how tests get collated into separate batches. Fixing this will later be necessary if tests get batched across a global suite, instead of only per CTest module.

2022-02-18 05:01 UTC, evanchia-ly-sdets requested changes

2022-02-18 05:01 UTC, evanchia-ly-sdets commented on Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
> +                result = Result.Unknown(test_spec=EditorSharedTest)
Here and for the rest of the same- Should we add some extra information for this Result? Could pass in something useful in the extra_info arg to be printed.

2022-02-18 05:04 UTC, Kadino commented on Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
> +                                    test_spec_list: list[EditorSharedTest], extra_cmdline_args: list[str] = None) -> None:
It's at least not a pep8 violation, but I'm happy to make this change

2022-02-18 17:55 UTC, Kadino commented on Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
> +                                    test_spec_list: list[EditorSharedTest], extra_cmdline_args: list[str] = None) -> None:
Appears that removing the spaces for type-hinted parameter values creates a pep8 warning, so I'll not make this change

2022-02-18 23:43 UTC, evanchia-ly-sdets approved these changes

2022-02-19 07:52 UTC, Kadino commented on Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
> +                warnings.warn(f"Test deselected from execution queue due to {ex}")
Apparently the previously broader exception clause was required, particularly for pytest exception-types including Skip which all extend BaseExceptions. This should now catch everything, record it as a warning, but not ignore system interrupts.

2022-02-21 18:43 UTC, merged