Remove AzCoreTestCommon, move related files to AzTest library
o3de/o3de pull request #8086
Opened 2022-03-04 23:42 UTC by burelc-amzn

AzCoreTestCommon includes headers from AzTest, and AzTest requires
symbols that are in AzCoreTestCommon. This change removes that circular
dependency.

Signed-off-by: Chris Burel <burelc@amazon.com>

2022-03-14 20:22 UTC, AMZN-ScottR commented on Code/Framework/AzTest/AzTest/AzTest.h
> +            s_benchmarkRegistry.AddBenchmarkEnvironment(std::unique_ptr<BenchmarkEnvironmentBase>{ benchmarkEnv });
This has some behavioural changes that I don't think are intended.  The first of which is the `BenchmarkEnvironmentRegistry` env variable is no longer being created, so the calls to `FindVariable` in the `AZ_BENCHMARK_HOOK*` macros won't process registered environments.

2022-03-14 21:28 UTC, Kadino commented on Code/Framework/AzTest/AzTest/UnitTest.h
>  #include <AzTest/AzTest.h>
I need a bit to mull over this change, particularly in regards to enshrining the UnitTest namespace as an example to other modules.

2022-03-14 21:28 UTC, Kadino commented on Code/Framework/AzTest/AzTest/aztest_files.cmake
> +    MockComponentApplication.cpp
AzTest is used by many libraries and does not include mocks that are specific to them. What is the argument for AzCore mocks living inside AzTest? Should they not exist in a separate sister library?

2022-03-15 21:07 UTC, Kadino commented on Code/Framework/AzTest/AzTest/UnitTest.h
>  #include <AzTest/AzTest.h>
Interesting, the UnitTest header/namespace had already been injected into AzTest.

2022-03-21 16:47 UTC, Kadino commented on Code/Framework/AzTest/AzTest/UnitTest.h
>  #include <AzTest/AzTest.h>
I'm okay with this dependency moving into AzTest, though not most of the other files

2022-03-21 16:54 UTC, Kadino requested changes

2022-03-21 16:54 UTC, Kadino commented on Code/Framework/AzTest/AzTest/aztest_files.cmake
>  set(FILES
I've convinced myself that UnitTest and TestTypes can move into AzTest, but I'll need an explanation on why all test modules will need the other files proposed in this move.

2022-10-03 17:48 UTC, closed without merging