Atom Tools: Removing shadow catcher opacity from lighting presets
o3de/o3de pull request #8586
Opened 2022-03-28 17:36 UTC by gadams3

The setting will be moved to viewport settings in a follow up PR

Signed-off-by: Guthrie Adams <guthadam@amazon.com>

2022-03-28 19:24 UTC, rgba16f approved these changes

2022-03-28 19:39 UTC, gadams3 commented
> @gadams3 do you have a link to the other PR you mentioned? The reason the setting was originally included in the lighting preset data was because the shade catcher is not a physically correct effect, meaning it has to be customized to look good for different lighting situations. In the new setting, is there some way that the shadow catcher is tuned for each lighting preset? Or does the user have to adjust it themselves separately?

The follow up PR will come shortly after this one. I'm attempting to break an 80 file branch, consolidating the viewport code from multiple tools as discussed, into multiple PRs.

When the shadow catcher was originally added, there used to be a comment and it was always my understanding that it was added to the lighting preset because there was nowhere else at the time. The setting will be available on the lighting preset panel with the shadow catcher toggle.

2022-03-28 19:46 UTC, AMZN-mnaumov approved these changes

2022-03-28 20:47 UTC, santorac commented
> When the shadow catcher was originally added, there used to be a comment and it was always my understanding that it was added to the lighting preset because there was nowhere else at the time. The setting will be available on the lighting preset panel with the shadow catcher toggle.

In that case it was my mistake to not clearly comment what I was thinking. When I implemented the shadow catcher and made each lighting preset have a shadow catcher opacity setting, the motivation was definitely as I described above. I would prefer to maintain a simple workflow where the user picks a lighting preset, and the shadow catcher opacity automatically adjusts to look good with the selected preset. I'm okay with changing the way that's achieved, but if the user has to manually adjust the shadow catcher each time they select a different lighting preset, that's a regression of the feature.

I'm curious what @HogJonny-AMZN thinks about this change.

2022-03-28 20:49 UTC, santorac requested changes
Let's resolve the above discussion before merging this please.

2022-03-29 21:35 UTC, santorac approved these changes

2022-03-30 14:58 UTC, merged