Sort search result by relevance to filter text
o3de/o3de pull request #8656
Opened 2022-03-31 23:03 UTC by onecent1101

## Details
Sort the search result to help find target node easier
Logic:
if item has children, we check against the minimum sorting score from its children including itself
if item has no children, we just check against with its own sorting score

Sorting score logic:
1. item string match with filter, return -1
2. item string contains filter or filter regex, return item string length (assume shorter name has stronger relevance)
3. if none, return max int

https://user-images.githubusercontent.com/5900509/161163442-1ccb374f-cad9-4123-ba7c-b81bd047f808.mp4

Signed-off-by: onecent1101 <liug@amazon.com>

2022-03-31 23:11 UTC, carlitosan requested changes

2022-03-31 23:11 UTC, carlitosan commented on Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.cpp
> +        if (sourceString.compare(m_filter, Qt::CaseInsensitive) == 0)
Move this check up, right after you initialize the model so that a match is an early return past the other, unused logic in this case.

2022-04-04 14:51 UTC, cgalvan approved these changes

2022-04-05 19:47 UTC, lsemp3d approved these changes

2022-04-07 17:33 UTC, carlitosan approved these changes

2022-04-07 17:35 UTC, merged