Fixed Cloth gem sample assets.
o3de/o3de pull request #9175
Opened 2022-04-25 23:17 UTC by micronAMZN

Cloth materials are all doublesided and won't generate warnings when opened in Material Editor. Assetinfos have proper cloth mesh modifier assignments. Prefab cloth components reference cloth objects.

Signed-off-by: Mike Cronin <58789750+micronAMZN@users.noreply.github.com>

2022-04-26 06:32 UTC, micronAMZN commented
This fix is for the updated Wind Provider tutorial. When integrating some feedback I noticed issues with the Cloth sample assets. https://github.com/o3de/o3de.org/pull/1473

2022-04-26 09:29 UTC, moraaar requested changes

2022-04-26 09:29 UTC, moraaar commented on Gems/NvCloth/Assets/Objects/cloth/Environment/Cloth_Blinds.fbx.assetinfo
> +                        "meshNodeName": "RootNode.pPlane1",
I don't know what's causing that many changes in the cloth assets. But I've noticed that the nodes names have changed, which can affect the node selected in Cloth Components in levels. So my initial worry is that the levels of automated cloth tests (located here `o3de\AutomatedTesting\Levels\NvCloth`) might not be setup correctly anymore.

I'll sync to the branch to verify the assets. I'll try to do it today, but it most likely happen tomorrow.

2022-05-03 14:49 UTC, amzn-jillich approved these changes

2022-05-03 16:29 UTC, merged