Added sig-graphics-audio to CODEOWNERS
o3de/o3de pull request #9466
Opened 2022-05-10 21:55 UTC by galibzon

Signed-off-by: galibzon <66021303+galibzon@users.noreply.github.com>

2022-05-10 22:48 UTC, gadams3 approved these changes

2022-05-10 22:59 UTC, jromnoa requested changes
Seeing these errors:
```
Unknown owner on line 124: make sure the team @o3de/sig-graphics-audio exists and has write access to the repository
…/sig-graphics-audio-reviewers @o3de/sig-graphics-audio
Unknown owner on line 125: make sure the team @o3de/sig-graphics-audio exists and has write access to the repository
…/sig-graphics-audio-reviewers @o3de/sig-graphics-audio
```

is this ok?

2022-05-10 23:12 UTC, amzn-phist commented
You can also add audio mappings:
```
/Gems/Audio*/  @o3de/sig-graphics-audio-reviewers @o3de/sig-graphics-audio-maintainers 
/Gems/Microphone/  @o3de/sig-graphics-audio-reviewers @o3de/sig-graphics-audio-maintainers 
```

2022-05-12 19:03 UTC, jromnoa approved these changes

2022-05-16 16:47 UTC, amzn-phist commented on .github/CODEOWNERS
> +/Gems/Terrain/ @o3de/sig-graphics-audio-maintainers @o3de/sig-graphics-audio-reviewers @o3de/sig-graphics-audio
You can remove `@o3de/sig-graphics-audio`, you only need the `reviewers` and `maintainers` groups.

2026-07-05 12:29 UTC, closed without merging