Fix for test script NewScriptEventButton_HappyPath_ContainsSCCategory
o3de/o3de pull request #9487
Opened 2022-05-11 21:14 UTC by michleza

adjusted logic in step 6, which caused flaky test behavior
replaced a bunch of strings with constants
reorganized the script a bit to be more readable.

2022-05-11 22:29 UTC, FuzzyCarterAWS requested changes

2022-05-11 22:29 UTC, FuzzyCarterAWS commented on AutomatedTesting/Gem/PythonTests/scripting/NewScriptEventButton_HappyPath_ContainsSCCategory.py
> +from scripting_utils.scripting_constants import WAIT_TIME_3, SCRIPT_CANVAS_UI,ASSET_EDITOR_UI, NODE_PALETTE_QT
space between each import entry for consistency

2022-05-11 22:29 UTC, FuzzyCarterAWS commented on AutomatedTesting/Gem/PythonTests/scripting/NewScriptEventButton_HappyPath_ContainsSCCategory.py
> +        helper.wait_for_condition(lambda: general.is_pane_visible(SCRIPT_CANVAS_UI), WAIT_TIME_3)
Is there an issue with reducing the wait time here? What's been identified as the root cause of the test failure here? Are these standard workflows that we're using and correcting bad test consistency?

2022-05-11 22:29 UTC, FuzzyCarterAWS commented on AutomatedTesting/Gem/PythonTests/scripting/NewScriptEventButton_HappyPath_ContainsSCCategory.py
> +        helper.wait_for_condition(lambda: not general.is_pane_visible(ASSET_EDITOR_UI), WAIT_TIME_3)
Is there an issue with reducing the wait time here? What's been identified as the root cause of the test failure here? Are these standard workflows that we're using and correcting bad test consistency?

2022-05-11 22:29 UTC, FuzzyCarterAWS commented on AutomatedTesting/Gem/PythonTests/scripting/NewScriptEventButton_HappyPath_ContainsSCCategory.py
>          frame = node_palette.findChild(QtWidgets.QFrame, "searchCustomization")
Is this a one-off node pallet child or should we be constant parameterizing this value as well?

2022-05-11 22:29 UTC, FuzzyCarterAWS commented on AutomatedTesting/Gem/PythonTests/scripting/NewScriptEventButton_HappyPath_ContainsSCCategory.py
>      script_event = "New Script event created in Asset Editor"
Previous tests have used the the `var = ('pass condition message', 'fail condition message')`, why is that pattern not being used here?

2022-05-16 21:07 UTC, FuzzyCarterAWS approved these changes
LGTM

2022-05-16 21:38 UTC, lsemp3d approved these changes

2022-05-16 21:40 UTC, merged