Use ScriptCanvas Editor to author ScriptEvents [PREVIEW]
o3de/o3de pull request #9796
Opened 2022-05-27 00:29 UTC by carlitosan

2022-05-31 23:53 UTC, lumberyard-employee-dm requested changes

2022-05-31 23:53 UTC, lumberyard-employee-dm commented on Code/Framework/AzCore/AzCore/IO/IOUtils.h
> +
The OpenMode enum should be forward declared

```suggestion
namespace AZ::IO
{
    enum class OpenMode : AZ::u32;
}
```

2022-06-01 00:08 UTC, lumberyard-employee-dm requested changes

2022-06-01 00:08 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Asset/EditorAssetSystemComponent.cpp
> +
Using namespace is banned at [global or namespace scope](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#namespaces).

This causes so many issues with name clashes in the past: https://github.com/o3de/o3de/pull/7184
Remember it is not just names from the ScriptCanvas libraries that are being introduced here.

Any dependency of ScriptCanvas like AzCore, AzFramework or a WinAPI name could now start causing clashing issues with ScriptCanvas names.

2022-06-01 00:15 UTC, lumberyard-employee-dm requested changes

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.cpp
> +    using namespace ScriptCanvas;
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
> +                        }
nitpick: extra whitespace at the end of this line.

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Components/EditorUtils.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Framework/Configuration.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponentSerializer.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Settings.cpp
> +        using namespace ScriptCanvas;;
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Utilities/RecentAssetPath.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.cpp
> +using namespace ScriptCanvas;
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.h
> +    namespace Editor
FYI: The C++17 nested namespace declaration can be used here to save an indentation level
```suggestion
namespace ScriptEvents::Editor
{
```

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/FileSaver.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/ParsingUtilitiesScriptEventExtension.cpp
> +    using namespace ScriptCanvas::Nodes::Core;
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:15 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/ParsingUtilitiesScriptEventExtension.cpp
> +    using namespace ParsingUtilitiesScriptEventExtensionCpp;
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:16 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_FileHandling.cpp
> +
Repeat: the `using namespace ScriptCanvas;` call needs to be moved to function scope or removed altogether

2022-06-01 00:17 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/ParsingUtilitiesScriptEventExtension.cpp
> +
This particular use case of using namespace ScriptCanvas is actually OK, because it is restricted to function scope.

2022-06-02 23:04 UTC, carlitosan commented on Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
> +                , QObject::tr("Graph defines a ScriptEvent. Press 'Discard' and use Script Event menu to save it as .scriptevent, or 'Ok' to continue to save as .scriptcanvas")
It works, but as a script canvas graphs, not a script event. They are each managed separately, but only for the preview step.

2022-06-03 00:22 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
> +                        }
Extra whitespace is still here

2022-06-03 00:23 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Framework/Configuration.h
> +
Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:23 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Framework/Interpreter.h
> +
repeat: Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:25 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Assets/ScriptCanvasFileHandling.h
> +        }
FYI the `inline` keyword isn't needed here.
It is only needed for an `out(of)line` definition

2022-06-03 00:25 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/EditorScriptCanvasBus.h
> +
Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:25 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/Utilities/RecentAssetPath.h
> +
Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:26 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/AssetGraphSceneDataBus.h
> +
Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:26 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.h
> +
Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:29 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
> +        const AZStd::string assetPath = AZStd::string::format("%s/scriptcanvas", resolvedProjectRoot.c_str());
This should use AZ::IO::FixedMaxPath::operator/ for appending the paths together and `AZ::Utils::GetProjectPath` for retrieved the projectpath
```
const auto assetPath = AZ::IO::FixedMaxPath(AZ::Utils::GetProjectPath()) / "scriptcanvas";

2022-06-03 00:30 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
> +        OnSaveToast(AZStd::string_view tabName, AZ::EntityId graphCanvasGraphId, bool saveSuccessful, AZStd::optional<AZStd::string> discriptionOverride = AZStd::nullopt)
typo: discription
```suggestion
        OnSaveToast(AZStd::string_view tabName, AZ::EntityId graphCanvasGraphId, bool saveSuccessful, AZStd::optional<AZStd::string> descriptionOverride = AZStd::nullopt)
```

2022-06-03 00:32 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.h
> +
repeat: Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:32 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/FileSaver.h
> +
repeat: Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:33 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/ModelTraits.h
> +
repeat: Shouldn't this be `using SourceHandle = ScriptCanvas::SourceHandle;`?

2022-06-03 00:33 UTC, lumberyard-employee-dm requested changes

2022-06-03 00:33 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
> +
This `using namespace ScriptCanvas;` is still at namespace scope

2022-06-03 00:38 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
> +    }
You could use AZStd:fill_n here
```suggestion
        AZStd::fill(AZStd::back_inserter(result), depth, '\t');
```

2022-06-03 00:39 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
> +        // ...can be deprecated ECS management
What does this comment mean?

2022-06-03 00:42 UTC, lumberyard-employee-dm commented on Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.h
> +        }
You may also want to provide `operator!` as well.

That would support cases such as 
```
SerializationResult result{false};
if (!result)
{
}

2022-06-03 00:50 UTC, lumberyard-employee-dm commented on Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventSystem.cpp
> +            AZ::IO::FileIOStream filestream(path.c_str(), AZ::IO::OpenMode::ModeRead);
This can use the AZ::IO::FileeReader class instead

2022-06-03 17:37 UTC, lumberyard-employee-dm approved these changes

2022-06-03 22:33 UTC, merged