SSAO null render P1 test expansion
o3de/o3de pull request #9844
Opened 2022-05-31 20:43 UTC by smurly

Extends null render tests for SSAO to cover P1 properties.

Report:
[SUCCESS] Success: SSAO Entity successfully created
[SUCCESS] Success: Entity has a SSAO component
[SUCCESS] Success: UNDO Entity creation success
[SUCCESS] Success: Entity has a SSAO component
[SUCCESS] Success: SSAO component disabled
[SUCCESS] Success: Entity has a PostFX Layer component
[SUCCESS] Success: SSAO component enabled
[SUCCESS] Success: Enable SSAO property set
[SUCCESS] Success: Enable SSAO property set
[SUCCESS] Success: Enable Blur property set
[SUCCESS] Success: Enable Blur property set
[SUCCESS] Success: SSAO Strength property set
[SUCCESS] Success: SSAO Strength property set
[SUCCESS] Success: Sample Radius property set
[SUCCESS] Success: Sample Radius property set
[SUCCESS] Success: Blur Strength property set
[SUCCESS] Success: Blur Strength property set
[SUCCESS] Success: Blur Edge Threshold property set
[SUCCESS] Success: Blur Edge Threshold property set
[SUCCESS] Success: Blur Sharpness property set
[SUCCESS] Success: Blur Sharpness property set
[SUCCESS] Success: Enable Downsample property set
[SUCCESS] Success: Enable Downsample property set
[SUCCESS] Success: Enable Downsample property set
[SUCCESS] Success: Enable Downsample property set
[SUCCESS] Success: Strength Override property set
[SUCCESS] Success: Strength Override property set
[SUCCESS] Success: SamplingRadius Override property set
[SUCCESS] Success: SamplingRadius Override property set
[SUCCESS] Success: Enable Blur Override property set
[SUCCESS] Success: Enable Blur Override property set
[SUCCESS] Success: Blur Const Falloff Override property set
[SUCCESS] Success: Blur Const Falloff Override property set
[SUCCESS] Success: Blur Depth Falloff Strength Override property set
[SUCCESS] Success: Blur Depth Falloff Strength Override property set
[SUCCESS] Success: Blur Depth Falloff Threshold Override property set
[SUCCESS] Success: Blur Depth Falloff Threshold Override property set
[SUCCESS] Success: Enable Downsample Override property set
[SUCCESS] Success: Enable Downsample Override property set
[SUCCESS] Success: Entered game mode
[SUCCESS] Success: Exited game mode
[SUCCESS] Success: Entity is hidden
[SUCCESS] Success: Entity is visible
[SUCCESS] Success: Entity deleted
[SUCCESS] Success: UNDO deletion success
[SUCCESS] Success: REDO deletion success
Test result:  SUCCESS

.\scripts\ctest\ctest_entrypoint.cmd --build-path atom_dev --suite main --ctest-executable "C:\Program Files\CMake\bin\ctest.exe" --config profile --tests-regex "AutomatedTesting::Atom_Main_Null" --generate-xml
Test project D:/workspace/o3de/atom_dev
    Start 162: AutomatedTesting::Atom_Main_Null_Render_00.main::TEST_RUN
1/4 Test #162: AutomatedTesting::Atom_Main_Null_Render_00.main::TEST_RUN ...   Passed   35.82 sec
    Start 163: AutomatedTesting::Atom_Main_Null_Render_01.main::TEST_RUN
2/4 Test #163: AutomatedTesting::Atom_Main_Null_Render_01.main::TEST_RUN ...   Passed   32.48 sec
    Start 164: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN
3/4 Test #164: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN ...   Passed   40.48 sec
    Start 165: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN
4/4 Test #165: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN ...   Passed   35.58 sec

100% tests passed, 0 tests failed out of 4

Signed-off-by: Scott Murray <scottmur@amazon.com>

2022-06-01 15:48 UTC, gadams3 approved these changes

2022-06-02 17:34 UTC, jromnoa requested changes

2022-06-02 17:34 UTC, jromnoa commented on AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SSAOAdded.py
> +        # 925. Test IsHidden.
typo here, should be `# 25.`

2022-06-03 01:14 UTC, jromnoa approved these changes

2022-06-03 17:08 UTC, merged