Submit testing asset for animation
o3de/o3de pull request #9874
Opened 2022-06-02 07:20 UTC by amzn-rhhong

Signed-off-by: rhhong <rhhong@amazon.com>

2022-06-04 20:44 UTC, lsemp3d approved these changes

2022-06-06 14:46 UTC, galibzon requested changes
Per @hultonha comments, please add a  README.md here so future generations don't miss on why these files exist.

2022-06-07 02:00 UTC, amzn-rhhong commented
@hultonha @galibzon updated the readme file

2022-06-07 07:01 UTC, amzn-jillich approved these changes

2022-06-07 12:58 UTC, hultonha approved these changes

2022-06-07 12:58 UTC, hultonha commented on AutomatedTesting/TestAssets/Animation/AlphabetP/Readme.txt
> +Freeze transform vs Non Freeze Transform
nit: Can you please include the exact asset names here for each case just to make it crystal clear, otherwise looks great! Thanks for adding this 👍

2022-06-08 12:29 UTC, hultonha commented
@galibzon Can you please remove 'request changes' now @amzn-rhhong as added a ReadMe. Thanks!

2022-06-09 21:37 UTC, galibzon commented on AutomatedTesting/TestAssets/Animation/AlphabetP/Readme.txt
> +Description: The non free transform version has an arbitrary transform on the root joint, while the freeze transform version has identical transform on the root joint.
Typo: `non free` vs `non freeze`

2022-06-09 21:37 UTC, galibzon approved these changes

2022-06-10 04:31 UTC, merged